### ISSUE TITLE
[Feature Request] Store of gestures / touchbar buttons 

### ISSUE THREAD

**Issue by MathieuCorti** [fifafu/BetterTouchTool#1055]
When looking at some feature request/ideas, I've seen great buttons ideas for touch bar. And it could be really great to have something like a store where users can share their creation, for those who have a lack of imagination or competencies with apple script! 

By the way, really great job you've done here, I can not live without it now.

**Comment by fakearchitect** [comment]
I was looking for something like that too, but didn't find anything, so I created a subreddit for the purpose: [BTTusercontent](http://www.reddit.com/r/BTTusercontent). It obviously has no content yet, but I thought I should put it out there :)
If you want to get over there and give me some input or submit a preset, that would be awesome!

**Comment by fifafu** [comment]
I will soon (2-3 weeks) present a little platform for sharing presets. Stay tuned :-)

**Comment by fakearchitect** [comment]
That's awesome, it'll be so cool to have an official platform! I think it really triggers people to put in a little extra work to make more refined stuff if they can share it and get feedback.

My little project went dormant quite quickly, since I was pretty much the only one submitting any presets although the sub had like 200 subscribers... I'll be sure to point the remaining 142 people to the platform when it goes live :)

Thanks for all your work, the app is dope! 💯
