### ISSUE TITLE
Excessive process generation

### ISSUE THREAD

**Issue by d-a** [fifafu/BetterTouchTool#1087]
I've recently decided to try out BetterTouchTool after installing High Sierra (doing a clean install to avoid any installation issues with the new APFS file system). Today I noticed I had abnormally high PIDs, new processes had an ID of over 50,000. As I've only installed a few apps I decided to find out the cause. Seeing nothing in system.log or in Activity monitor I decided to give execsnoop a try. There is I saw the following repeat every 5 seconds:

```
STRTIME                UID    PID   PPID ARGS
2017 Jun 17 21:40:11   501    887    588 sh
2017 Jun 17 21:40:11   501    888    887 ioreg
2017 Jun 17 21:40:11   501    889    887 grep
```
So I checked what process 588 was, and found out it was BetterTouchTool. Creating 3 processes every 5 seconds ends up being 51,840 over a 24 hour period which explains why PIDs would be so high after a day.

Is this some kind or bug or does BetterTouchTool need to check something in ioreg every 5 seconds?

Type of Mac: 2013 15" rMBP
macOS version: 10.13 Beta 1
BetterTouchTool version: 2.21

**Comment by fifafu** [comment]
Hey,

Yes, BTT is executing some terminal commands every ~5 second in order to get information about various system states (e.g. to check whether the macbook is put into clamshell mode)

There are hidden settings to disable this, but it can cause BTT to enter a inconsistent state / not be synced with the system state
