### ISSUE TITLE
 picture in picture mode in safari

### ISSUE THREAD

**Issue by chessisamazing27** [fifafu/BetterTouchTool#1193]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I have created a small action to enter picture in picture mode in safari which right clicks on a youtube video, delays .2 second, right clicks again, delays 0.2 seconds again, hits the down arrow 3 times and then the enter key to select "enter picture in picture mode". While this function works sometimes, most of the time BTT carries out the functions in reverse order, right clicking once then hitting the down arrow key three times reducing the youtube video volume and then right clicking again, clicking twice after the first right click and then clicking once after the second right click or clicking once after the first right click and then clicking twice after the second right click. This means the wrong option gets clicked most of the time. 

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by kamykaze** [comment]
I really like our gesture, so I recreated this in my settings, and it worked fine. Can you share what gesture you use to trigger this? I find that sometimes the gesture you use can mess with your expected behavior. I'm using 3 finger double-tap for mine.

For example, if you use a modifier to trigger the gesture, specially a click, you can end up with the wrong click, which would then bring up different menus. Also, if you use a gesture that may cause the mouse cursor to move (tipswipe, for example) you may end up right clicking the wrong spot.

Here's my suggestion for debugging:

1. use a very obscure trigger to start (I like using Function keys or custom trackpad tap sequence) and turn on HUD display of the gesture so you know the right gesture was triggered
2. Add one action at a time. At each step, test the gesture and check if you end up where you want.
3. Increase delays so you know there's enough time for menus to show up (you can decreased them once you rule out they are not the issue)

From your description it sounds like you could be using a gesture that's moving the mouse cursor or something.

Also,something you can try if you can't afford to change your gesture and it's causing mouse movement issue is to add a 'move mouse to position' action so mouse motion won't be a problem.

**Comment by chessisamazing27** [comment]
I have been activating this function through a touchbar button and a keyboard shortcut, and while it works sometimes it is very unreliable. If possible could you please send me a picture of your exact set of instructions. I have tried your debugging solution and tried to use a touchpad gesture however I still encountered unreliability. 
[recording.mp4.zip](https://github.com/fifafu/BetterTouchTool/files/1140559/recording.mp4.zip)

**Comment by kamykaze** [comment]
@chessisamazing27 I'm not sure what exactly is going on, but I found a better action to use for this functionality. Try this:

In Safari specific gestures, set a gesture, and add the following actions:

1. Right Click
2. Delay Next Action by 0.25 seconds (start with a higher number just to be safe)
3. Trigger Context Menu Item (use 'Enter Picture in Picture' as value)

You'll notice that this relies less on arrow keys and enter (which can trigger unexpected items, and only uses 1 delay, so it's quicker and more reliable.

good luck

**Comment by fifafu** [comment]
I think @kamykaze solution is currently the best way to achieve this, thus I’m closing here for now!
