### ISSUE TITLE
Newbie can't even get BTT to work :-(

### ISSUE THREAD

**Issue by SkiAddict1** [fifafu/BetterTouchTool#1209]
Downloaded BTT yesterday, tried to set it up so that my Magic Trackpad can zoom the screen (i.e. with no keypresses needed) so that I can read the screen from across the room.

On launch, BTT tells me the trial is expired.  Since there was a button to extend the trial I pressed it.  Set up a Pinch Out trackpad shortcut, with action Smart Zoom since that's all that seemed appropriate to choose.  Turned on both "Zoom in or out" and "Smart zoom" in Sys Prefs.  Also set up a Pinch In trackpad shortcut with action Smart Zoom.

However, pinching in and out does nothing.

Your documentation on trackpads seems to be non-existent.

I would like to use your product but currently I'm about ready to throw it in the Trash.  I hate having to contact the developer about something which is probably very simple to resolve, but what else am I to do?

**Comment by kamykaze** [comment]
Hi, I'm not the developer, but I've been using BTT for years so maybe I can help you out.

Before anything, it's worth mentioning that BTT handles gestures/shortcuts, and it does so very well, but zooming is part of the OS functionality. BTT simply provides an easy access to the Smart Zoom, but sounds like that's not what you need.

From what I can tell, SmartZoom is an app specific feature that handles how much to zoom in/out based on where your mouse cursor is. That's why if you use the system's double tap to smartzoom on say, the BTT preferences, nothing happens. It's great when it works well (namely Preview), but I personally don't like when an app is guessing what I'm trying to do.

With that said, if you want to zoom your entire screen (not just the app), you can toggle an Accessibility feature in OS X. 

First, go to System Preferences > Accessibility > Zoom, then turn on the "use keyboard shortcuts to zoom"

Now you can zoom the window in/out using Cmd+Opt+= and Cmd+Opt+- 
I know it's not what you want yet since you're trying to avoid the keyboard. But check if that's the functionality you want. At this point you can also go in options and tweak the minimum and maximum zoom to your liking.

Next, you'll need to turn on the zoom in or out shortcut in preferences so that BTT can detect that gesture. Go to System Preferences > Trackpad > Scroll & Zoom, and turn on "Zoom in or out". You don't need Smart zoom unless you care for it. That's something separate.

Now go to BTT >  Trackpads > Add New Gesture. Select one of the Pinch Out gestures (I prefer the one with Thumb and 2 fingers to avoid false triggers, but it's up to you), and assign the keyboard shortcut Cmd + Opt + =

Add another gesture for Pinch In and assign the shortcut Cmd + Opt + -

Test those gestures out to see if you get the desired zooming.  Unfortunately with this gesture you're detecting it only once, so you can't do a smooth zoom as with some native apps.

If you need you can tweak the zoom settings in System preferences.

PS: Alternatively, you can use BTT remote to zoom in/out your screen, control your mouse cursor, etc. without needing to use a magic trackpad. I set mine up so I can use the volume buttons on my iphone to zoom in/out my screen.

**Comment by SkiAddict1** [comment]
Hi kamykaze, thank you so much for responding!  I've followed your instructions (see screenshot of my BTT window), cmd+option+= and cmd+option+- do exactly what I want, but zoom from my trackpad still isn't happening :-(  Is it possibly because it thinks the trial period has ended?  I downloaded the app yesterday, so as far as I can see I've followed the instructions for how to avoid/fix that problem.

![untitled](https://user-images.githubusercontent.com/30161721/28194538-0b21124a-6899-11e7-9ed2-bcd257cb70ef.jpg)

**Comment by fifafu** [comment]
Or important thing to note:

BetterTouchTool doesn't have an "extend trial" button you mentioned. If the trial is over it won't work.

**Comment by SkiAddict1** [comment]
OK, so my terminology wasn't exact: the actual name of the button is "Continue Trial..."   But I only downloaded the thing yesterday!!  And there's a notice on the developer's front page talking about some mistake he/she made which meant that trials were ending sooner than they should, and people should download the latest version to fix the problem.  Since the notice is dated 27 April I have to assume that the version I downloaded yesterday fixes it, no?

![untitled](https://user-images.githubusercontent.com/30161721/28200252-0ce9a346-68bf-11e7-8350-15279d9320fb.jpg)

**Comment by fifafu** [comment]
Did you have a previous version installed earlier?

That is definitely a bug, it should never show the continue trial button and the expiration warning at the same time. I'll look into that later today!

The message from my blog doesn't apply to current versions anymore.

**Comment by SkiAddict1** [comment]
No, I had never heard of BTT before yesterday.

**Comment by kamykaze** [comment]
Make sure you turned on the zoom in or out setting in System preferences. A quick way to tell if the gesture is being triggered or not is to click the settings button (little gear icon) and turn on HUD display with a message. Also try switching gestures to see if that works.

**Comment by fifafu** [comment]
@skiaddict1 does it also say trial expired if you click on the menubar icon? (If so it definitely expired).

The BetterTouchTool window will still work if the trial is over but most actions won't execute anymore.

**Comment by SkiAddict1** [comment]
Yes, it does say trial expired:
![untitled1](https://user-images.githubusercontent.com/30161721/28201020-39e30a6e-68c3-11e7-9e94-f2887d10bf50.jpg)

kamykaze yes the zoom is turned on, I can zoom the screen with cmd+option+= and -.  Have defined HUD display but nothing shows.  Guess I need to figure out why it thinks it's expired...

**Comment by fifafu** [comment]
Did you maybe change the date of your Mac recently?

Unfortunately one of BTT's security mechanisms triggered and you won't be able to get back on trial.
You could go to the about tab in BetterTouchTool , then click "Export debug information" and send me the content of the BetterTouchTool debug folder that's placed on your desktop (boastr.net@gmail.com)
I'll be able to see what caused the trial ending then.

**Comment by SkiAddict1** [comment]
OK, have done that, thanks.

**Comment by SkiAddict1** [comment]
Happy zoomer am I :)  With fifafu's help BTT is now working and it's doing exactly what I wanted, more or less -- the zoom isn't very smooth, but I know that's because of Apple not BTT.  It turns out that several simulated keypresses can be sent from one pinch out/in, so I'm getting multiple zoom steps per pinch.  Many thanks to all here who got me on the right track.
