### ISSUE TITLE
[Feature request] Show button if condition is met

### ISSUE THREAD

**Issue by mattorp** [fifafu/BetterTouchTool#1247]
#### Affected input device
Mainly touch bar.

#### Description
Being able to check for conditions would help bring the touch bar into another gear. I mainly use the touch bar in full BTT mode, but I miss the feedback the standard mode provides, like changing the play/pause icon. Additionally it would be possible to show if the song was liked, in the library (quickly add if not**), if more songs will play after the current, etc. 

A ton of other applications, that are scriptable, would also allow for a more dynamic touch bar just like the original mode. I really hope you will be able to get around to this. BTT has already made the touch bar a must for me, but conditions would really kick it up a notch. 

Thank you for the work you do. BTT is what makes the touch bar truly interesting. 

**  If Apple gets around to update the iTunes Applescript.

**Comment by fifafu** [comment]
Hey,

I think you can already do this if you use the Apple Script widget.
If the Script returns an empty string the button will be hidden.

If this doesn't help please comment again, then I'll reopen the issue.

**Comment by mattorp** [comment]
Yes, I don't know why I thought the Apple script widget would be unable to do this. 

Really amazing work you do! I can't see myself at a computer without the touch bar and BTT anymore.

**Comment by Merott** [comment]
Hey there @fifafu!

Is an interval the only way to make the Apple Script run?

I'm trying to implement the play/pause toggle, and unless I've misunderstood something, using the Apple Script widget and an interval for that purpose comes at an unnecessarily big performance cost.

An interval of more than 0.2 seconds makes the button appear slow to respond, because it won't update the appearance of it until the next run, but setting such a low interval causes the Apple Script run to run multiple times per second, which is really not needed until the button is pressed. This causes increased CPU usage.

It would be nice to have the option to not use an interval, but instead only run the AppleScript when the button is tapped.

Please let me know if I've misunderstood something.

And thank you for BTT. I hated the Touch Bar, until I realised the potential of it with BTT!
