### ISSUE TITLE
Request: option to make buttons as toggles (with two icons)

### ISSUE THREAD

**Issue by iAmRenzo** [fifafu/BetterTouchTool#1314]
The buttons on the TouchBar are now just buttons with one icon. But in some cases I have them tied to a toggle function, like show/hide hidden files in Finder. It would be nice to have two icons to the button: one 'on' and the other 'off'. Now the icon is the same, and you can't see which state the toggle is.

**Comment by mkhalife** [comment]
I had a similar need and after some searching I found this method that works: https://github.com/fifafu/BetterTouchTool/issues/838#issuecomment-299023824

> ...you can use the Apple Script widget, but leave the script box empty. Then assign the predefined action "run apple script (enter directly as test)".
> 
> Now every time the button is pressed it will execute that predefined action and deliver the result to the widget.

You just have to write the toggle as an Apple Script instead of using the predefined action:

```
set state to do shell script "defaults read com.apple.finder AppleShowAllFiles" as string
if state is "0" then
	do shell script "defaults write com.apple.finder AppleShowAllFiles -bool TRUE"
	do shell script "killall Finder"
	return "on"
else
	do shell script "defaults write com.apple.finder AppleShowAllFiles -bool FALSE"
	do shell script "killall Finder"
	return "off"
end if
```

And then your "Advanced Configuration" settings for the widget should look something like this:

<img width="834" alt="screen shot 2017-09-03 at 11 25 54 pm" src="https://user-images.githubusercontent.com/28989127/30010774-49ed5986-9100-11e7-8d36-dd5b61ec78d9.png">

You can even take this a step further and add an Apple Script in the widget to check the status of the toggle every few seconds. This was important for me because I wanted to check whether my docker container was running and display the appropriate button. Since the container can be started/stopped by other means (e.g. machine reboot) I wanted to make sure it was always showing the right button.
