### ISSUE TITLE
[Feature request] sync, but not enable of functions

### ISSUE THREAD

**Issue by ZappoB** [fifafu/BetterTouchTool#1442]
Hi,

it would be really great, if the status enabled/disabled would not be synchronised, so I can sync all functions, but can choose on which system they are enabled.

Thanks for reading.

**Comment by patrickrushton** [comment]
+1 for this. Alternatively (or additionally) it would be great if the enabled/disabled presets would not be synchronised. That way I could have a universal set of presets that I sync across all my macs, and then can choose to enable additional presets specifically for each Mac (handy because each of my Macs have different setups with and without Wacoms, trackpads, etc.)

**Comment by fifafu** [comment]
I will add a new trigger to the "Other" section in BTT.
This trigger will be called "After launching on Mac with Serial Number". This action will allow you to enter the serial number of the Mac on which it will be executed. You can then e.g. assign the predefined action "Switch to Preset", which allows you to select which presets you want to enable on that specific system.

This will be included in the next update.

**Comment by ZappoB** [comment]
Thank you very much!
