### ISSUE TITLE
Three finger dragging has gotten dramatically worse with the new updates

### ISSUE THREAD

**Issue by cleverjackal** [fifafu/BetterTouchTool#1470]
So I know that it's been [talked about before](https://github.com/fifafu/BetterTouchTool/issues/1340) (I also submitted one myself a really long time ago.

Basically fifafu seems to think that this is an unsolvable issue which is due to Apple's implementation of the three finger drag, or something like that. I never completely liked this explanation, because I noticed that BTT only interfered with certain apps. For most apps, my three finger drag would work normally. However, for other apps, such as PDF Expert and even Xcode, three finger drag would be the most unpredictable, annoying, infuriating gesture ever.

Well, I updated to the latest stable release (2.300) after a really long time recently, and unfortunately what I can see is that the three finger drag has stopped working properly in pretty much all apps (such as the Finder, Safari, etc. even though they never were a problem before).

I just wanted to mention this. I'll be downgrading most likely but I hope this issue can be solved.

**Comment by fifafu** [comment]
Ah that's because I disabled the three finger drag compatibility mode in the current alpha because I noticed it caused various performance problems for normal drags.

In the next version I'll add a check whether thee finger dragging is used and in case it is I'll enable the compatibility mode again (with all it's issues).

Unfortunately I still think this can not be solved by an external app unless Apple changes the way the Three Finger Drag generates it's events. (As soon as the three finger drag is enabled some of the fundamental properties of the trackpad change and I can not workaround this)

**Comment by cleverjackal** [comment]
Okay, I see. By the way, just FYI: the problem I am facing is that the three finger drag a split second after I start dragging. So if I wanted to start dragging from the beginning of this sentence, it would start selection from the "o".

I'll look out for the next version!

**Comment by cleverjackal** [comment]
@fifafu Could you kindly let me know what the latest version of BTT is, which had three finger drag compatibility?

**Comment by Spirarel** [comment]
@cleverjackal you might be interested in [the new setting for improved compatibility](https://github.com/fifafu/BetterTouchTool/issues/1531#issuecomment-333361272). I came here looking for a fix as you did, and this works very well so far.

**Comment by cleverjackal** [comment]
@Spirarel thanks a lot! Btw, I'm actually the OP of the issue you linked to ;)
