### ISSUE TITLE
Any chance of BTT remote for Android in the future?

### ISSUE THREAD

**Issue by Etregoning** [fifafu/BetterTouchTool#1524]
#### Description of bug/feature request/question:
I love my Macbook, but unfortunately I'm not a huge fan of the iPhone. Is there any chance of creating a BTT remote app for Androids in the future? I know I can't possibly be the only Macbook lover that prefers Android for mobile.

**Comment by fifafu** [comment]
Unfortunately currently there are no plans for BTT Remote for Android. It's possible that I'll release a lite version based on React Native (which I'm currently experimenting with), but it won't include all features of the iOS version and I can't give a timeframe or even promise it'll ever be released :-(
(sorry I'm mostly developing for iOS and macOS because Android always really annoys me when developing apps for it :-))

**Comment by jimmywarting** [comment]
+1
Don't think this should be closed.

**Comment by Etregoning** [comment]
For some reason, I never saw the previous reply. It's all good man, I realize we all have time constraints. I noticed you are using an Apache license, so I may consider forking it and trying to see if I can get something going, I just figured I would ask first!

Thanks for the reply!

**Comment by francwalter** [comment]
I use for remote things on my MacBook with Android the App Tasker, where I set some Tasks and Scenes to launch commands via ssh. 
It works and is highly self-customizable.
If you interested, I can send you the Task and Scene as xml, but you will need a rooted Android phone and the paid app "Tasker" then.

**Comment by fifafu** [comment]
There is now also a way to trigger BTT commands on Android using the new integrated webserver 

https://docs.bettertouchtool.net/docs/webserver.html

I will soon post a tutorial about how to set this up.

**Comment by francwalter** [comment]
Not available under 2.426, I guess this needs the new license?
