### ISSUE TITLE
Desktop Preview Workaround not working properly after HighSierra Update

### ISSUE THREAD

**Issue by lollerino** [fifafu/BetterTouchTool#1571]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I was using this workaround to show the desktop thumbnails in Sierra while using Multi Touch:

4 Finger Swipe UP | Mission Control
--> Save Current Mouse Position
--> Delay next action by 0.03 seconds
--> Move mouse to X:50.00 Y:0.00
--> Restore Saved Mouse Position

After the HighSierra Update it won't react at a delay time of and below 0,26 seconds. At 0,27 seconds it works just fine, but it's way too slow for a proper usage. Thanks for your help in advance!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
 Trackpad

#### Device information:

Type of Mac: Mid 2012
macOS version: HighSierra (10.13)
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry there is nothing you can do to make it faster as far as I know. You can use the predefined action "show mission control & open desktop previews" but it  may be even slower.

**Comment by lollerino** [comment]
Alright. Strange, that it worked while using Sierra though. Thanks anyway!

**Comment by bigyellowmonkey** [comment]
make the delay longer.

**Comment by fifafu** [comment]
Unfo

**Comment by zenkjn** [comment]
Hi there, I know this is awhile, but I came across this on google search, and wanted to share my workaround. Hope this helps. Basically, move your mouse to top before Mission Control action.

4 Finger Swipe UP | Save Current Mouse Position
--> Move mouse to X:50.00 Y:0.00
--> Mission Control
--> Delay next action by 0.01 seconds
--> Restore Saved Mouse Position

**Comment by lollerino** [comment]
Hey zenkjn! Thx for answering and sharing your workaround. Somehow it doesn't work out for me, just shows the standard mission control without any desktop previews.

**Comment by fifafu** [comment]
That's the reason why BTT has a dedicated action for this - these workarounds do not work consistently on all machines because the timing is different everywhere. BTT's action is a bit slower but should work everywhere.

**Comment by lollerino** [comment]
Good to know. Been using the standard BTT action since a few weeks already, because the workaround is not working anymore, doesn't matter how long I set the delay.

**Comment by lollerino** [comment]
For anyone who is having the same issue like me. Just figured out an alternative: I activated a Hot Corner for Mission Control in the upper right and I use this command lines in BTT: 

4 Finger Swipe UP | Save Current Mouse Position
--> Move mouse to X:1439.00 Y:0.00
--> Delay next action by 0.01 seconds
--> Restore Saved Mouse Position

Works just fine without any delay.

**Comment by kachkaev** [comment]
Thanks @lollerino – this trick worked for me! The responsiveness is not perfect, but things are somewhat better than what I used to have with BTT's special gesture instead of a hot corner. At least the previews are shown every time, not depending on how quickly I swiped up. Here's what is still glitchy:

* BTT's _3/4 fingers up_ gesture requires more 'swipe distance' before it gets detected compared to the native macOS gesture.
* I can no longer use a reverse _3/4 finger swipe down_ gesture to close mission control once it's opened – have to go for another _3/4 finger swipe up_ or _esc_

The StackExchange [answer](https://apple.stackexchange.com/a/213096/73253
) that helped me find BTT suggests sending Apple your complain via a feedback form. I've already done so and highly recommend this to others: https://www.apple.com/feedback/macos.html This slightly increases our chances to permanently save ourselves from this UX pain in one of the future releases.
