### ISSUE TITLE
Only use TouchBar features?

### ISSUE THREAD

**Issue by somebee** [fifafu/BetterTouchTool#1577]
I'm loving the TouchBar features in BTT, but feel uncomfortable with BTT hijacking the trackpad etc. Right now I have big issue where everything I do seem to start dragging-gestures (especially in iTerm), and a few months ago every tap registered as 2 taps in safari and chrome. These issues goes away when I quit BTT. Is there any way to just use the TouchBar functionality?

**Comment by fifafu** [comment]
Unfortunately these issues are not caused by hijacking the trackpad (BTT only enables the trackpad support when gestures are configured in BTT)

They are caused by a current bug in macOS in combination with some specific APIs that  BTT requires for many functions.

However I'm currently adding workarounds for all problematic apps until the issue is resolved on the OS level.

You can also disable BTT for specific apps (Click the menubar icon and select "disable for active app")
