### ISSUE TITLE
Three finger drag not working properly in Alfred Preferences

### ISSUE THREAD

**Issue by xilopaint** [fifafu/BetterTouchTool#1603]
#### Description of bug/question:
Three finger drag not working properly in Alfred Preferences.

More details here:

https://www.alfredforum.com/topic/10773-allow-moving-multiple-nodes-with-three-finger-drag/?tab=comments#comment-55571

#### Affected input device:
MacBook Trackpad

#### Device information:
Type of Mac: MacBook Air Mid 2011
macOS version: 10.13
BetterTouchTool version: 2.310 (687)

**Comment by cleverjackal** [comment]
I have similar issues to this in PDF Expert, Xcode, and Sketch. They mess with three finger drag. I don't think it's possible to fix this, as I've reported these issued before.

@fifafu Would it be possible to disable _only trackpad gestures_ in these apps? I usually disable BTT completely in these apps because of the three finger drag issue which is specific to the aforementioned apps, but that gets rid of the keyboard shortcuts.

**Comment by xilopaint** [comment]
It's fixed.
