### ISSUE TITLE
Mouse clicks release too slow

### ISSUE THREAD

**Issue by BassTony** [fifafu/BetterTouchTool#1639]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I have a constant issue with my mouse clicks. The release of the click is so slow, that my system interprets my clicks as drags when I move my mouse after clicking.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Mouse

#### Device information:

Type of Mac: MJLT2 (MacBook Pro mid 2015)
macOS version: Sierra
BetterTouchTool version: 2.310 (687)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by okdana** [comment]
It sounds like i might have this same problem, though i'm using the track pad. It's most noticeable to me when i'm in the Terminal:

1. I click the Terminal content area for some reason
2. I click on another Terminal tab
3. As the tab is switching, i notice that the tab i was on previously has scrolled up and turned blue, as if i had selected some text and started dragging upwards
4. If i switch back to the previous tab it is in fact scrolled up and some text is selected

I feel like this started happening semi-recently, like within the past few months, but i can't say for sure. I thought maybe my track pad was dying or something, but just today it occurred to me to quit BTT, and that instantly fixed the problem.

As far as i can tell this only happens when i actually *click*, not when i tap.

Literally the only reason i have BTT is to set three-finger tap to middle-click. I use none of the other features, have never messed with any of the other settings, that is the only thing i have set.

My info:

* MacBook Pro, mid-2015, 15" (MacBookPro11,5)
* Internal track pad
* macOS Sierra 10.12.4
* BetterTouchTool 2.310

It's probably not super helpful, but here's a screen-shot depicting the result i described above (after switching to the second tab and then back again):

<img width="906" alt="screen shot 2017-10-21 at 15 40 32" src="https://user-images.githubusercontent.com/122095/31855740-b7520d64-b676-11e7-91a6-3636c507d060.png">

**Comment by BassTony** [comment]
Hey!

I just remembered that this issue plagues me also on the internal force trackpad. When using PowerPoint, for example, clicking slide thumbnails on the left pane in a quick succession gets the slides reordered. It seems almost like after the first click if I click too soon again without lifting my finger from the trackpad, BTT translates the second click as a drag-and-drop action starting from the first clicked position and ending at the current position.

Hope this helps in tracing the place in the code.

-T

**Comment by fifafu** [comment]
Could you check whether 2.313 alpha fixes this?

**Comment by okdana** [comment]
I've only been using it for a few minutes, but i think it's working for me so far. Will report back if i have any issues. Thanks!

**Comment by BassTony** [comment]
Hi,

Seems to work OK in the mentioned problem cases so far. I’ll let you know in a couple of days if the problem shows up again.

-T

**Comment by Hawkcode** [comment]
Hi I put in a ticket and have not heard anything. The problem I found is in drawings. I went to add one and the second I lift my finger off the mouse the drawing disappears.

I have not found any work around.


--Richard S Albrecht--
2019 Salem Rd
Elgin, IL 60123
847-652-3563

Skype: HawkCode
