### ISSUE TITLE
Update notification issue

### ISSUE THREAD

**Issue by sagitt** [fifafu/BetterTouchTool#168]
i've 3 macs, with same btt settings (new settings done after os x installation, no pref file copy-paste)

on 1 of these 3 macs i can't see new updates, it's tell me that btt are server updated, but on other macs i can see the update, and i've to copy-paste the .app file on my 3rd mac.

even on manual check.

(enabled alpha update etc...)

**Comment by fifafu** [comment]
Some updates are currently only available for Touch Bar computers, may it be that?

**Comment by sagitt** [comment]
I see updates on non-touchbar macs and I can't see update on my touchbar macbook..

**Comment by fifafu** [comment]
Weird, however the next big update will synchronize all update channels again. I probably forgot some specific setups :-)

**Comment by sagitt** [comment]
thanks :)

**Comment by fantaaaaaa** [comment]
has this already been fixed? i to have had some cases where the newest update would not load automatically. i left out three updates (i think alphas) due to the app not checking for updates itself... :)

**Comment by fifafu** [comment]
it checks but not all the time (to reduce server load). Because of this updates (especially alpha updates) may be delayed a bit for some users.

I'm closing here for now as the current situation is intended. Not all macOS version get updates at the same time (recent versions get the update first because I always test on the current macOS version). Also e.g. specific Mac models may be targeted sometimes.

Version 2.01 will be the stable release that will soon be available for all machines. Currently it's available for 10.10.x-10.12.x
