### ISSUE TITLE
macOS 10.13.2 Beta (17C60c) breaks gestures in BTT

### ISSUE THREAD

**Issue by frenchbeast** [fifafu/BetterTouchTool#1693]
#### Description of bug/feature request/question:
OSX 10.13.2 Beta (17C60c) breaks gestures in BTT
After reboot/upgrade BTT doesn't take any gesture from the trackpad
The live view will show nothing happening.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad, Magic Mouse and Siri Remote 

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2015)
macOS version: OSX 10.13.2 Beta (17C60c)
BetterTouchTool version: 2.311 (688)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
I haven't found a workaround yet.
I tried to reboot the laptop, restart BTT etc ..

---

**Note by BTT developer, October 5**: The current alpha (2.313) partially fixes support for trackpads. Force trackpads should work ok. Non-force trackpads work, but click gestures are not yet supported. Siri Remote works ok. Unfortunately Magic Mice can't be supported unless Apple allows me to use the old API again.

**Comment by fifafu** [comment]
Thanks for reporting! I'm currently not at home but will look into it this weekend. Let's hope it can be fixed.

**Comment by fifafu** [comment]
In case you can see any related log messages in the macOS console.app, please post them here.

**Comment by frenchbeast** [comment]
Unfortunately the console is quiet for the gesture part.
I can see logs related to keyboard actions though.

**Comment by blkbit** [comment]
> default	15:50:38.784537 -0400	loginwindow	Startup | kLWDBLogTAL | kLWDBLogLevel_Internal | -[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : BetterTouchTool
> default	15:50:38.867355 -0400	launchservicesd	CHECKIN:0x0-0x7b07b 1177 com.hegenberg.BetterTouchTool
> default	15:50:38.868292 -0400	loginwindow	Startup | kLWDBLogTAL | kLWDBLogLevel_Internal | -[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : BetterTouchTool
> default	15:50:38.901882 -0400	BetterTouchTool	UNIX error exception: 17
> default	15:50:38.929724 -0400	BetterTouchTool	UNIX error exception: 17
> default	15:50:38.934146 -0400	BetterTouchTool	UNIX error exception: 17
> default	15:50:38.939029 -0400	BetterTouchTool	UNIX error exception: 17
> default	15:50:39.271461 -0400	kernel	[HID] [MT] [Error] AppleMultitouchDeviceUserClient::initWithTask BetterTouchTool is not entitled
> default	15:50:39.271514 -0400	kernel	[HID] [MT] [Error] AppleMultitouchDeviceUserClient::initWithTask BetterTouchTool is not entitled
> default	15:50:39.488768 -0400	BetterTouchTool	MacOS error: -67052
> default	15:50:39.492610 -0400	BetterTouchTool	UNIX error exception: 17
> default	15:50:39.496666 -0400	BetterTouchTool	UNIX error exception: 17
> default	15:50:40.788654 -0400	BetterTouchTool	MacOS error: -67052
> default	15:50:41.732075 -0400	kernel	[HID] [MT] [Error] AppleMultitouchDeviceUserClient::initWithTask BetterTouchTool is not entitled
> default	15:50:41.732097 -0400	kernel	[HID] [MT] [Error] AppleMultitouchDeviceUserClient::initWithTask BetterTouchTool is not entitled
> default	15:50:41.732257 -0400	kernel	[HID] [MT] [Error] AppleMultitouchDeviceUserClient::initWithTask BetterTouchTool is not entitled
> default	15:50:41.732282 -0400	kernel	[HID] [MT] [Error] AppleMultitouchDeviceUserClient::initWithTask BetterTouchTool is not entitled
> default	15:50:41.733179 -0400	kernel	[HID] [MT] [Error] AppleMultitouchDeviceUserClient::initWithTask BetterTouchTool is not entitled
> default	15:50:41.733236 -0400	kernel	[HID] [MT] [Error] AppleMultitouchDeviceUserClient::initWithTask BetterTouchTool is not entitled
> default	15:50:41.733272 -0400	kernel	[HID] [MT] [Error] AppleMultitouchDeviceUserClient::initWithTask BetterTouchTool is not entitled
> default	15:50:41.733344 -0400	BetterTouchTool	Bonjour Service Published: domain(local.) type(_bttremote._tcp.) name(blktop) port(53981)
> default	15:50:49.402371 -0400	BetterTouchTool	LSExceptions shared instance invalidated for timeout.
> default	15:50:49.476590 -0400	BTTRelaunch	LSExceptions shared instance invalidated for timeout.

Here's what I'm seeing in console when I open BTT in 10.13.2 beta

**Comment by fifafu** [comment]
Ah, that’s pretty bad as it means Apple now requires third party apps that
want to get the raw touchpad data to have an Entitlement only Apple can
create. I'm not sure whether I can get such an entitlement, but I'm trying
to contact Apple immediately.

Best
Andreas

Am 31.10.2017 um 14:00 schrieb blkbit <notifications@github.com>:

default 15:50:38.784537 -0400 loginwindow Startup | kLWDBLogTAL |
kLWDBLogLevel_Internal | -[ApplicationManager
checkInAppContext:refCon:eventData:] | checked in app : BetterTouchTool
default 15:50:38.867355 -0400 launchservicesd CHECKIN:0x0-0x7b07b 1177
com.hegenberg.BetterTouchTool
default 15:50:38.868292 -0400 loginwindow Startup | kLWDBLogTAL |
kLWDBLogLevel_Internal | -[ApplicationManager
checkInAppContext:refCon:eventData:] | checked in app : BetterTouchTool
default 15:50:38.901882 -0400 BetterTouchTool UNIX error exception: 17
default 15:50:38.929724 -0400 BetterTouchTool UNIX error exception: 17
default 15:50:38.934146 -0400 BetterTouchTool UNIX error exception: 17
default 15:50:38.939029 -0400 BetterTouchTool UNIX error exception: 17
default 15:50:39.271461 -0400 kernel [HID] [MT] [Error]
AppleMultitouchDeviceUserClient::initWithTask BetterTouchTool is not
entitled
default 15:50:39.271514 -0400 kernel [HID] [MT] [Error]
AppleMultitouchDeviceUserClient::initWithTask BetterTouchTool is not
entitled
default 15:50:39.488768 -0400 BetterTouchTool MacOS error: -67052
default 15:50:39.492610 -0400 BetterTouchTool UNIX error exception: 17
default 15:50:39.496666 -0400 BetterTouchTool UNIX error exception: 17
default 15:50:40.788654 -0400 BetterTouchTool MacOS error: -67052
default 15:50:41.732075 -0400 kernel [HID] [MT] [Error]
AppleMultitouchDeviceUserClient::initWithTask BetterTouchTool is not
entitled
default 15:50:41.732097 -0400 kernel [HID] [MT] [Error]
AppleMultitouchDeviceUserClient::initWithTask BetterTouchTool is not
entitled
default 15:50:41.732257 -0400 kernel [HID] [MT] [Error]
AppleMultitouchDeviceUserClient::initWithTask BetterTouchTool is not
entitled
default 15:50:41.732282 -0400 kernel [HID] [MT] [Error]
AppleMultitouchDeviceUserClient::initWithTask BetterTouchTool is not
entitled
default 15:50:41.733179 -0400 kernel [HID] [MT] [Error]
AppleMultitouchDeviceUserClient::initWithTask BetterTouchTool is not
entitled
default 15:50:41.733236 -0400 kernel [HID] [MT] [Error]
AppleMultitouchDeviceUserClient::initWithTask BetterTouchTool is not
entitled
default 15:50:41.733272 -0400 kernel [HID] [MT] [Error]
AppleMultitouchDeviceUserClient::initWithTask BetterTouchTool is not
entitled
default 15:50:41.733344 -0400 BetterTouchTool Bonjour Service Published:
domain(local.) type(_bttremote._tcp.) name(blktop) port(53981)
default 15:50:49.402371 -0400 BetterTouchTool LSExceptions shared instance
invalidated for timeout.
default 15:50:49.476590 -0400 BTTRelaunch LSExceptions shared instance
invalidated for timeout.

Here's what I'm seeing in console when I open BTT in 10.13.2 beta

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fifafu/BetterTouchTool/issues/1693#issuecomment-340889266>,
or mute the thread

**Comment by intrepidsilence** [comment]
Oh no.  I sincerely hope you can get Apple to cooperate with you.  I seriously cannot live without BTT.  My workflow is completely dependent upon the wonderfulness that BTT has brought.  This is the last thing I expected to happen with a point rev update.  Waiting with baited breath...

**Comment by dtoub** [comment]
Noticed this issue immediately after installing the 10.13.2 seed. Have filed a BR with Apple. Let's see.

**Comment by fifafu** [comment]
I have a potential workaround, unfortunately it would increase CPU usage, so I'll wait before implementing it.

**Comment by pyummm** [comment]
please, implement as temporary solution, impossible to back to real mouse clicks, it kills me out

**Comment by fifafu** [comment]
Unfortunately it will probably take a few weeks until a solution is available as this will require to rewrite some core parts of BetterTouchTool and I'm not yet sure whether it will be possible to include all current features.

If possible please provide feedback to Apple to allow BTT to use the entitlement.

**Comment by gilliginsisland** [comment]
This is odd. I have two 13 inch retina macs. One with force touch, and one without, both running the 10.13.2 beta. On the one with force touch, bettertouchtool trackpad gestures do not work, and the live view shows nothing. But the one without force touch does work.

**Comment by intrepidsilence** [comment]
I have an iMac with external Magic TouchPad and it does not work.


Michael Spurlock
michael.spurlock@greyspaces.net

On November 2, 2017 at 10:32:16 AM, gilliginsisland (notifications@github.com) wrote:

This is odd. I have two 13 inch retina macs. One with force touch, and one without, both running the 10.13.2 beta. On the one with force touch, bettertouchtool trackpad gestures do not work, and the live view shows nothing. But the one without force touch does work.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fifafu/BetterTouchTool","title":"fifafu/BetterTouchTool","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fifafu/BetterTouchTool"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gilliginsisland in #1693: This is odd. I have two 13 inch retina macs. One with force touch, and one without, both running the 10.13.2 beta. On the one with force touch, bettertouchtool trackpad gestures do not work, and the live view shows nothing. But the one without force touch does work."}],"action":{"name":"View Issue","url":"https://github.com/fifafu/BetterTouchTool/issues/1693#issuecomment-341439959"}}}

**Comment by fifafu** [comment]
@gilliginsisland are you sure the update went through correctly? I think if your machine really was on 10.13.2 it couldn't work, regardless which kind of trackpad you use.

**Comment by gilliginsisland** [comment]
<img width="1280" alt="screen shot 2017-11-02 at 3 32 35 pm" src="https://user-images.githubusercontent.com/5375070/32346241-1886cc58-bfe3-11e7-8138-c0aa4de899a8.png">

**Comment by gilliginsisland** [comment]
no question about it, Im def running the beta

**Comment by dtoub** [comment]
Folks, BTT DOES work, at least on my system, for built-in laptop trackpads. I'm using it on my 2013 MBP. However, it absolutely positively does not work with my Magic Trackpad, and no gestures show up in live view. Given that my laptop is elevated on my desk, using that instead of the Magic Trackpad is not really feasible, so it will be wonderful if Apple can prioritize this.

**Comment by gilliginsisland** [comment]
Its not a question of built in, because my other laptop with force touch trackpad is not working.
So maybe its only the force touch that requires the new entitlement.

**Comment by intrepidsilence** [comment]
It is not related to only Force Touch as my plain old Bluetooth Magic Trackpad is not working.

**Comment by dtoub** [comment]
My Magic Trackpad is first generation. No 3D Touch whatsoever.

**Comment by fifafu** [comment]
Very interesting. I'll be back at home tomorrow (was on travel), with access to a few more machines. I'll do more testing then.

**Comment by fifafu** [comment]
@gilliginsisland, could you check whether system integrity protection is enabled on the system where BTT still works? (using this terminal command: ```csrutil status```)

**Comment by gilliginsisland** [comment]
@fifafu both machines, the one that works and the one that doesn't do not have SIP enabled.

**Comment by gilliginsisland** [comment]
@fifafu also both machines are running the latest alpha of bettertouchtool 2.311

**Comment by fifafu** [comment]
Oh well, at least some good news: got most basic gestures working again already, so watch out for the next alpha later this weekend. It will use a completely different API and I hope Apple won't take that away in the future.

Some features won't be possible with the alternative API though, I'll put more information in the release notes.

**Comment by pyummm** [comment]
F5 my favorite key at this page

**Comment by gilliginsisland** [comment]
@fifafu just out of curiosity, do u have an idea as to why it would work on one machine and not another?

**Comment by rltbennett** [comment]
Just another data point: 2015 rMBP with (built-in) force touch trackpad: trackpad gestures not working at all. SIP is enabled.

**Comment by wanyaxing** [comment]
CAN NOT accept the life without BTT, I will  back to 10.13.1 for ever. 

:(

**Comment by nguyenhimself** [comment]
Is it pedantic of me to ask for the title to be renamed from "OSX 10.13.2" to "macOS 10.13.2"? 😐

**Comment by FlyingCodeMonkey** [comment]
My MacBook doesn't have ethernet (fecking USB-C only MacBook Pro) is it worth wasting a day reverting to 10.13.1 from Time Capsule via WiFi, or are you likely to get the alpha/beta version out this weekend as you mentioned above? Not trying to rush you, just trying to avoid wasting time!

**Comment by fifafu** [comment]
There will be a alpha this weekend, but in a first step it will only fix the basic gestures like taps, top taps and swipes. Maybe also clicks for force touch trackpads (not sure yet how to handle older trackpads). And I have not yet checked Magic Mouse support.

**Comment by FlyingCodeMonkey** [comment]
Thanks. I'll wait and see how the alpha goes.

**Comment by m00nc0re** [comment]
Happy to have found this thread.... been using BTT for several years and was happy to contribute for the development... impatiently waiting for the next Alpha which could fix the problems I'm having since installing the latest Mac OS Beta. Thanks fifafu.

**Comment by ddriver88** [comment]
Yes, amazing support from this developer. Fiafafu, you are the man.

**Comment by ZAUmusic** [comment]
I too am looking forward to a fix. I'm upset that BTT isn't currently working. I realize now how big a role BTT plays in my workflow, it's like I've lost a limb or something....

**Comment by milch** [comment]
`com.apple.hid.multitouch.user-access` is the new entitlement that is needed to access the trackpad. If you're a developer, create a Radar asking Apple to make that entitlement available to other mac app developers and don't restrict it to Apple apps only

**Comment by fifafu** [comment]
@milch, yep I have done that already.

**Comment by fifafu** [comment]
You can try this version for now: https://bettertouchtool.net/releases/btt2.312.zip

- Should restore most functionality on Force Touch Trackpad and Siri Remote
- Does not restore functionality on Magic Mice
- Click gestures won't work on non-force-touch trackpads

This is still less than optimal, I really hope Apple will allow me to use the old API again.

**Comment by dtoub** [comment]
Wow. Thank you. It works perfectly for me (Magic Trackpad 1, no click gestures).

**Comment by FlyingCodeMonkey** [comment]
Thanks so much for the super-quick turnaround. MacBook Pro (Late 2016 touch bar model with force click trackpad) and all gestures appear to work correctly.

**Comment by cdplayin** [comment]
THANK YOU! This is running perfectly on my current gen Mac Pro6,1 12-Core with dual D700's 3x LG 5K displays and TotalSpaces running 10.13.2. Got back my favourite Snow Leopard features. If anything comes up I'll update.

**Comment by pyummm** [comment]
Magic Mouse, pleaseee

**Comment by fKing** [comment]
it's been working on my 2016 macbook, on the 10.13.2 beta (have not tried it on my 2015 mbp, because of the logic pro issue). still will DL the version posted above, see how that goes...

**Comment by ediskrad73** [comment]
seems the new Alpha breaks touchbar support, its frozen and unresponsive on my 2017 MBP

**Comment by slimnickyy** [comment]
thanks for the effort, but not the alpha 2.312 doesn’t help on a 2015 MacBook Air

**Comment by fifafu** [comment]
@pyumm unfortunately there is currently no API available that would allow magic mouse support. (Please provide feedback to Apple)

@ediskrad ah thanks for reporting, I'll fix that 

@slimnickyy seems to be working with the listed limitations on my air. What kind of gestures are you using?

**Comment by slimnickyy** [comment]
@fifafu apologies it is as you described i.e. gestures including a click don’t work. otherwise OK. thank you and hopefully it’ll be back to 100% in due course.

**Comment by fifafu** [comment]
https://bettertouchtool.net/releases/btt2.313.zip should fix the Touch Bar freezing issue (would be great if somebody could confirm, so I'll put it on the alpha update channel)

**Comment by m00nc0re** [comment]
Thanks for the quick update.. but I'll wait for a Magic Mouse fix

**Comment by fifafu** [comment]
@m00nc0re unfortunately there may never be one unless Apple allows the usage of the necessary API ;-(

**Comment by sparticvs** [comment]
@fifafu 2.313 alpha works for me and seems to fix my issues I was mentioning in #1704 .

**Comment by ediskrad73** [comment]
@fifafu new Alpha fixes touchbar support and gestures are working, thank you for the quick turnaround!

**Comment by dtoub** [comment]
One oddity that has nothing to do with BTT and everything to do with the 10.3.2 seed: tapping on a first-generation Magic Trackpad while the lock screen is on does nothing (I use MacID to have a tappable pattern to unlock my Mac). Tapping on my built-in trackpad is fine. I suspect Apple has broken other things besides BTT.

**Comment by fifafu** [comment]
Yeah MacID uses the same now disallowed framework as BTT. ;-(
However it's really weird that apparently some internal non-force trackpads seem to continue to work.

**Comment by m00nc0re** [comment]
I have an iMac 5K with Magic Mouse (which I love) I'm debating downgrading to get BTT working the way I want it to work... or getting a god damn $169 "magic" track pad.....!!

**Comment by fifafu** [comment]
I would recommend to wait for a  few more betas (depending on how much you need it) :-) there is still some hope Apple will change this again.

**Comment by fKing** [comment]
andreas,
wll be patient. am using BTT on my 12" macbook, where all is well, my macbook pro, where logic lives... logic is essential, so will leave it disabled for now.
thanks for being so on top of this!
f
    On Monday, November 6, 2017, 1:35:53 AM EST, Andreas Hegenberg <notifications@github.com> wrote:  
 
 
I would recommend to wait for a few more betas (depending on how much you need it) :-) there is still some hope Apple will change this again.

**Comment by fifafu** [comment]
Quick Update: 

- beta 2 still requires the entitlement.
- click gestures on normal trackpads should be back with the next update
- Magic Mouse support will probably be dead unless anything changes 😢

**Comment by m00nc0re** [comment]
![madmonkey](https://user-images.githubusercontent.com/33352456/32469004-b3013852-c31e-11e7-972a-0dcf1535e1b8.gif)

Thanks for the update.

**Comment by m00nc0re** [comment]
Where can I annoy Apple to make this happen?

**Comment by fKing** [comment]
[https://www.apple.com/feedback/macos.html](url)

but don't hold your breath (sigh)....

**Comment by milch** [comment]
@m00nc0re If you are a registered developer with Apple, you can use https://developer.apple.com/bug-reporting/. As far as I know, the link that @fKing posted is for consumer issues, this would be a developer issue since they made a previously "public" API private by requiring an Apple-only entitlement.

**Comment by fifafu** [comment]
Just to be clear, the API was never officially public, but was pretty much common knowledge for the last 8 years. If you contact Apple you can point to my radar 35334701

**Comment by slimnickyy** [comment]
> click gestures on normal trackpads should be back with the next BTT update

@fifafu any ETA on this one? thanks

**Comment by fifafu** [comment]
@slimnickyy probably sunday evening

**Comment by hannesoid** [comment]
I filed an Apple developer bug report too
- radar: rdar://35425182
- openradar: http://openradar.appspot.com/radar?id=4952562675482624

Feel free to duplicate it, which is easy using https://github.com/br1sk/brisk

@fifafu let me know if my formulations in it are terribly inacurrate, I really don't know much about the implementation issues `¯\_(ツ)_/¯ `

**Comment by m00nc0re** [comment]
I bought a Magic Trackpad 2.......................................................... it's okay but I have to add a finger to every gesture I had programmed with the Magic Mouse........ it's not as precise..... it's better for 3+ finger swipes though....... I hope they fix the Mouse issue.......... if they do I'm selling this trackpad.

**Comment by eggplantsplz** [comment]
hey @fifafu - thanks for your efforts in getting BBT gestures back on track while we await some of the more front-end things from Apple API access.
a couple things:
1. to confirm, things like three finger pinch to close/open gestures are still not working per the latest alpha release?
2. any ETA on when the next alpha release will be available?

Thanks!

**Comment by fifafu** [comment]
Before releasing the new alpha I'll await the next macOS beta.

I'm currently looking into various options to make BTT work like it did before the change. Possibly I can inject code into a system process that has the necessary entitlements and then forward the touch data to BTT (not very nice, but maybe there is no other way to achieve Magic Mouse support)

@eggplantsplz yes, unfortunately the basic touch data from the alternative API doesn't allow me to reliably recognize a thumb, thus the pinch gestures currently don't work

**Comment by MatiasGandolfo** [comment]
is back-!!!! In new beta works again!!!!

**Comment by fifafu** [comment]
Can confirm! I'll release an update in a few minutes that will revert the changes I made for the previous betas.

**Comment by eggplantsplz** [comment]
This is great news. Thanks for all of your continued efforts.

Just to confirm: this most recent beta is not yet Public right?

**Comment by fifafu** [comment]
Not yet!

**Comment by fifafu** [comment]
I uploaded btt2.314 which disables the changes again and should work fine on the newest beta: https://bettertouchtool.net/releases/btt2.314.zip

Happy to close here. Let's hope it will stay like this.
