### ISSUE TITLE
function key + media key not recognized as shortcut trigger

### ISSUE THREAD

**Issue by adamjrice** [fifafu/BetterTouchTool#1697]
#### Description of bug/feature request/question:

BTT does recognize the f-keys/media keys as shortcut triggers, but does not recognize them when combined with the "fn" key.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard (internal and external both)

#### Device information:

Type of Mac: MacBook Pro (retina late 2013 vintage)
macOS version: 10.13.1
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

This is to work around the change in Apple's handling of media keys.

**Comment by fifafu** [comment]
That's because depending on your settings FN will either switch the F keys to be media keys or the media keys to be F keys.

Unfortunately the media keys can not be captured by BTT for technical reasons. Thus this is indeed not fixable.

You may want to look into an app called Karabiner Elements. It integrates at a much lower level into the system and thus should be able to do this.

**Comment by adamjrice** [comment]
Thanks for the information on Karabiner Elements.
