### ISSUE TITLE
Some clicks are not registered on Shift application with a Magic Mouse

### ISSUE THREAD

**Issue by JeremyReynaud** [fifafu/BetterTouchTool#1706]
#### Description of bug/feature request/question:
If BTT is activated on Shift application (desktop mail manager: https://tryshift.com/), a lot of clicks are not registered by the app. Disabling BTT or quit it fixes the issue.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Mouse

#### Device information:

Type of Mac: iMac Retina 5K, 27-inch, 2017
macOS version: High Sierra 10.13.1
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Disabling BTT for Shift app.

**Comment by fifafu** [comment]
Ah thats caused by a bug in the Chrome engine. The Chromium team has already fixed it in the latest beta, but it will probably take a while until the fix reaches shiftit.... 
(Shiftit seems to be an electron app which uses the Chrome engine for rendering)

I'll apply the same workaround I apply to Chrome with the next BTT update.
