### ISSUE TITLE
Three finger click not working on Magic Trackpad 2

### ISSUE THREAD

**Issue by nckmr** [fifafu/BetterTouchTool#1728]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Three finger click is not working anymore for me. It always worked for me before on this computer and trackpad (I used it all the time for opening new browser tabs). I have tested it with different functions/actions and can't get it to work. 
If I pause BTT the three finger click works as normal, otherwise with BTT running it does not three finger click consistently and feels "flat" or non-responsive.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Trackpad 2

#### Device information:

Type of Mac: iMac (21.5-inch, Late 2012)
macOS version: 10.13.1 
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Mh I just checked on my two machines and it seems to be working fine.
Could you check what the settings in the advanced trackpad preferences under "Force Touchpad" look like? What value does the three finger slider show?
![image](https://user-images.githubusercontent.com/8820811/32702947-b0ffaca8-c7ee-11e7-9904-2055655e83e5.png)

**Comment by nckmr** [comment]
Thanks for the response. 

Here are my values. I tried a few days ago moving the 3 finger clicks higher and lower so it may be off the default (only after having problems).

**Comment by nckmr** [comment]
I tried another restart after deleting the action and putting it back in. It is working well now and I am happy with it. I had tried restarting before but not after removing the action. Thanks for checking!

**Comment by nckmr** [comment]
This stopped working for me again even after restarts. I want to mention that I found the solution in the advanced trackpad settings and selecting "New BTT normal click" (or any of the 'new' clicks seem to work). As shown above, I had the BTT default set.

**Comment by ylluminarious** [comment]
@nckmr +1 for deleting the action and putting it back in. I had the same sort of issue as well, and it was solved with your suggestion. Thanks!

**Comment by ylluminarious** [comment]
Your other suggestion about the advanced trackpad settings is also very helpful.

**Comment by ylluminarious** [comment]
Well, @nckmr's advice *was* working fine for a while, but I've been having the same old problems again recently. The only workaround I found this time is to attach a `Restart BetterTouchTool` action to the `Middle Click` action. I.e., I'm just automatically restarting BetterTouchTool after the middle click. That is pretty hacky and clunky, though. Please look into this issue more, @fifafu.

**Comment by ylluminarious** [comment]
@fifafu Actually, the issue seems like the left click (single-finger normal click) is conflicting with the three-finger click. Do you have any advice on how to work around that?

**Comment by ylluminarious** [comment]
To anyone seeing this thread, I have been able to get around the problems I have described above by using a 4-finger click instead of 3-finger click for my gestures. It takes a little more effort, but I have been using 4-finger click for `Middle Click` for about 2 weeks now and it seems to be working. I have only noticed a problem once where 4-finger click didn't respond and I restarted BTT. Hopefully it doesn't become a regular phenomenon...

**Comment by vfonic** [comment]
> @fifafu Actually, the issue seems like the left click (single-finger normal click) is conflicting with the three-finger click. Do you have any advice on how to work around that?

This is exactly what's happening to me. Is it possible to prevent default OS action when BTT detects registered action?

**Comment by fifafu** [comment]
@vfonic Do you use the system's three finger dragging? This may not be compatible with BTT's three finger drag unfortunately. In general BTT should block all left-clicks when a three finger click is registered.

**Comment by vfonic** [comment]
@fifafu I'm actually using BTT to set "Three Finger Tap" => "Mouse Middle Click" to be able to open a link in a new browser tab when detected.
Unfortunately, it only works together with macOS system's three finger tap (Lookup word under the mouse cursor), because, if I disable it, macOS fires left click (tap) and so I get this:
- new tab open (due to BTT's Middle Click action, which is great)
- navigate to the link under the cursor (due to system's left click/tap)

So, for me, this sort-of works if I have system's three finger tap => Lookup word and tap to click. I guess it's easiest to explain with video:
https://www.dropbox.com/s/e5ksu9rp2k5wgj8/Three%20Finger%20Tap.mov?dl=0
(this is me just doing Three Finger Tap)
If you have any suggestion how to get rid of annoying "Lookup word in dict", I'd be so thankful. :)
