### ISSUE TITLE
Conflict with "Unclutter" app

### ISSUE THREAD

**Issue by yuchenglin** [fifafu/BetterTouchTool#1791]
#### Description of bug/feature request/question:
Conflict with "Unclutter" app when using window snapping by moving window to corners.
The gray frame of snapping window will not show up when both apps are on.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Mouse

#### Device information:

Type of Mac: Macbook pro
macOS version: 10.13.1
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
https://unclutterapp.com/

**Comment by fifafu** [comment]
I can't seem to reproduce this, has it maybe been fixed in the uncultterapp?

**Comment by fifafu** [comment]
//edit after running unclutterapp for a while I think I can reproduce this. Let's see whether I can fix it on my side.

**Comment by fifafu** [comment]
Ok, I identified the issue and have added a workaround for the next version of BTT (alpha later today). This will fix it in 99% of the use cases, however the underlying problem is that Unclutter does some "hacks". Basically unclutter opens an invisible window on every click at the current mouse position (I don't know why but I assume it has to do with the dragging files to the top). Unfortunately this invisible window overlays the window under the cursor and BTT has no way to get the window behind.

The workaround I have added uses the focused window instead of the window under the cursor in case unclutter is detected. I have also sent an email to the unclutter team, let's see if there is the possibility for a better fix.
