### ISSUE TITLE
BTT preventing repeated touchpad clicks (and doubleclick too!)

### ISSUE THREAD

**Issue by Pash237** [fifafu/BetterTouchTool#1829]
#### Description of bug/feature request/question:
BTT preventing fast repeated clicks (i.e. doubleclick).
Double *taps* and repeated *taps* in general works fine.
It seems to me that very doubleclicks (less than 50ms?) works, but maybe they're just considered as taps.
Also, long doubleclicks (something like 400ms?) works too.

I have a force touchpad, so the clicks are not real clicks of course.

Removing all touchpad gestures and changing advanced settings (like Double-tap delay) doesn't help.
This issue clearly didn't exist before (don't sure if BTT update or macOS update broke it).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
built-in force touchpad

#### Device information:

Type of Mac: MacBook Pro 13'' 2015
macOS version: 10.13.1
BetterTouchTool version: 2.317

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Preferences and debug info:
https://www.dropbox.com/s/msrbx3sd2w4us9a/BetterTouchToolDebug.zip?dl=0
The only workaround for now is to close BTT :(

**Comment by fifafu** [comment]
Thanks for reporting!
I think in your case that bug is triggered due to the values you set for "1 finger force click" in the advanced trackpad prefs.
It should look like this:
<img width="1127" alt="grafik" src="https://user-images.githubusercontent.com/8820811/33530157-87b502ce-d87b-11e7-87c5-4e6534715f78.png">

So just put a higher number and you should be fine. Howver this is still a bug and I'll fix it with the next update!

**Comment by Pash237** [comment]
Wow, thank you!
Changing 1 Finger Click pressure to 250 fixes the issue!

However, I don't have any 1 Finger gestures set in BTT, so maybe they should not be registered (and therefore interfere with system clicks) at all.

**Comment by fifafu** [comment]
Yep that was a bug :-). I just fixed it, so this should not happen with the next version.
