### ISSUE TITLE
"Type Custom Text" Does Not work for @ 

### ISSUE THREAD

**Issue by s-gilroy** [fifafu/BetterTouchTool#1916]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I'm trying to have the "Type Custom Text" enter an email address but the @ symbol is shown as a 2. I'm assuming this is because the shift key is required to modify the 2 key to an @ symbol.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook keyboard

#### Device information:

Type of Mac: MacBook Pro 2017 13in
macOS version: 10.12.6
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
this seems to work correctly here, what kind of gesture/trigger are you using for it?

**Comment by s-gilroy** [comment]
I'm using CMD+SHIFT+A

**Comment by s-gilroy** [comment]
Hey Andreas, I think I found the issue! I'm using this shortcut to input emails into UITextFields in the iOS Simulator (I'm a mobile dev). It must be related to how the simulator translates keyboard presses?

**Comment by fifafu** [comment]
I think you are right - unfortunately I don't think I can fix this in BTT :-(
You could try to send a shortcut instead of using the type action.
 
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or still encounter this problem, please create a new issue - I'm now much more responsive than a few months ago.
