### ISSUE TITLE
Open Split View for Window doesn't work (High Sierra)

### ISSUE THREAD

**Issue by adamw** [fifafu/BetterTouchTool#1937]
#### Description of bug/feature request/question:

I've setup two shortcuts for native split view, but they don't work:

<img width="1015" alt="2017-12-29_1500" src="https://user-images.githubusercontent.com/60503/34438715-0537198a-eca9-11e7-9e4c-d766bd15f794.png">

When pressing the shortcut, nothing happens. Selecting another action (e.g. resize to 2/3) works fine.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac: MBP Retina Mid 2012
macOS version: 10.13.2
BetterTouchTool version: 2.320

**Comment by fifafu** [comment]
This only works for windows that support full-screen mode (and you shouldn't use a shortcut that includes shift to trigger it, otherwise it will be quite slow).

Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or still encounter this problem, please create a new issue - I'm now much more responsive than a few months ago.
