### ISSUE TITLE
Muting Gestures

### ISSUE THREAD

**Issue by ticktockner** [fifafu/BetterTouchTool#1956]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

It would be great to be able to 'mute' a gesture. For example, I have a TipTap set up for volume control but depending on what I'm working on it would be great to be able to go into the preferences and just mute those gestures temporarily without having to delete them.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook Trackpad

#### Device information:

Type of Mac: MacBook Pro 13" 2017
macOS version: High Sierra 10.13.2
BetterTouchTool version: 2.320

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

none. thanks for a great app!

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Here is what you could do:

*Click the manage presets button and create a new preset called e.g. "Volume Control".
*Temporarily make it the master preset and add your volume control gestures to that preset.
*Switch back to your previous preset
*Now you can activate the volume control preset whenever needed, and disable it otherwise. You can even do this using the predefined action "Switch to Preset"

![image](https://user-images.githubusercontent.com/8820811/34640016-71e60b8e-f2eb-11e7-9822-04d8ff700ac9.png)

**Comment by ticktockner** [comment]
Oh, cool I hadn't tried that! Thank you!

**Comment by jeffmann** [comment]
Sometimes when I'm testing new gestures, or troubleshooting, I'd like to turn off certain gestures without having to delete them and then re-create them. Like right now, I want to turn off "tip tap left" to see if it's causing a problem. I wish there was an extra column in the gestures list, with a checkbox for every gesture to enable or disable it. Thanks!

**Comment by fifafu** [comment]
Tracking this here: #2129
