### ISSUE TITLE
[Bug] BTT touch bar Escape key doesn't work in Cmd+Tab App Switcher

### ISSUE THREAD

**Issue by vladmoroz** [fifafu/BetterTouchTool#1988]
#### Steps
1. Enable 'Show ESC Button on the left side of the Touch Bar' in BTT touch bar settings
2. Make sure BTT's ESC button is visible instead of the system ESC
3. Press and hold Cmd+Tab within the app that was customized. App Switcher should appear.
4. Press ESC

Actual result: nothing happens
Expected: the custom ESC button closes the App Switcher like a system's ESC would

#### Device information:

Type of Mac: Macbook Pro 2017 with Touch Bar
macOS version: 10.13.2
BetterTouchTool version: 2.324

**Comment by dredboi** [comment]
I also have this issue.  Same device info as 'vladmoroz'.

**Comment by Worie** [comment]
It doesn't occur on version 3.332 (MBP 2014 13", 10.13.1, Touch Bar emulated)

**Comment by vladmoroz** [comment]
@Worie I can still reproduce it on 2.332 on my device

**Comment by dredboi** [comment]
confirmed still an issue on 2.332 for me

**Comment by fifafu** [comment]
Unfortunately macOS disables all custom TouchBar buttons when either the app switcher or mission control is active. I have not yet found a workaround for this.

However I really recommend to change the Capslock key to ESC in System Preferences => Keyboard => Modifier Keys. It takes a bit getting used to it, but it's better than the Touch Bar replacement esc...

**Comment by AnthoPakPak** [comment]
Hi @fifafu ! I found this bug really annoying with app switcher… 
Initially I thought it was the TouchBar behavior, but I've found that when quitting BetterTouchTool, it works well !
Indeed, all buttons seems disabled when app switcher is active, except 'esc' key. I think the issue is because you emulate the key isn't it ?
Is it possible to look into it once again to see if there's isn't any possibility to fix it ?

Thanks in advance 😀

**Comment by AnthoPakPak** [comment]
@fifafu I've noticed that with the option to show FN touches when pressing fn key (in System Preferences), if we press it while app switcher is open, we get the default esc key and we can dismiss the app switcher. So I think a workaround is possible. I've tried to remap "CMD + TAB" to "CMD + TAB" + "fn key down", but it doesn't bring the FN touches as it does with the keyboard key...

@tuomassalo The best workaround i've found for now is following : 
![image](https://user-images.githubusercontent.com/16854916/44843226-197c4f00-ac48-11e8-9ecd-230fded1e0eb.png)
I've assigned a keyboard shortcut "CMD + @" to "esc" key (because the @ key is just over the TAB key on my AZERTY keyboard). This way, you can dismiss app switcher with clicking the key just over TAB, it's better than previous suggested solutions :)

**Comment by RamRS** [comment]
The workaround above has a bug. If I were to dismiss BTT using the `X` touch button, and after a few seconds press `Cmd`, when I release the `Cmd` the BTT panel appears again. Given that I dismissed it, should it not stay dismissed? Is the on-Cmd-release trigger enabling BTT irrespective of what the pre-Cmd-press setting was?
