### ISSUE TITLE
[Feature Request] ability to add specific gestures/touch bar buttons for alfred search

### ISSUE THREAD

**Issue by amatrosovas** [fifafu/BetterTouchTool#2035]
Not sure if this is possible now but I could not find a way to do this. I would like to be able to show custom touch bar buttons when entering Alfred search.

**Comment by fifafu** [comment]
Unfortunately I don't think this is possible for now, as Alfred doesn't behave like a normal application. BTT never receives a notification that the active application has changed, because Alfred doesn't really change the active application (which is a good thing, otherwise Alfred wouldn't work).

I'll close here for now, but keep it in mind if I ever come across a good solution for such apps.
