### ISSUE TITLE
Window moving/resizing does not work properly for Preview.app

### ISSUE THREAD

**Issue by posburn75** [fifafu/BetterTouchTool#2048]
#### Description of bug/feature request/question:

The window moving/resizing hotkeys do not work when trying to move/resize a Preview window _unless_ the cursor is already in the window titlebar or at the edge of the window. This, of course, defeats the purpose of having a hotkey set up to move/resize a window from anywhere in that window.
This issue also affects the System Preferences window, and possibly others.

#### Device information:

Type of Mac: MBP (Retina, 15-inch, mid 2015)
macOS version:  10.13.4 Beta (17E139j)
BetterTouchTool version:  2.332 (713)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately currently there is a bug in preview/quicklook/ all apps that use the same component which makes it impossible for BTT to get the window which is currently under the cursor.
I hope Apple will fix this, but I may have a workaround ready soon.

I'm tracking this issue here: https://github.com/fifafu/BetterTouchTool/issues/1982
