### ISSUE TITLE
[feature request]   Is there a kind  of  BTT can be using in iMac  bootcamp ?

### ISSUE THREAD

**Issue by tigerpa666666** [fifafu/BetterTouchTool#2102]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Is there a kind  of  BTT can be using in iMac  bootcamp ?

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by jeffmann** [comment]
Not the same as BTT, but useful: http://trackpad.forbootcamp.org/ - for iMac, I guess you mean Magic Trackpad, now there is http://extramagic.forbootcamp.org/ . They're both free to use (donations are asked for), but not open source.

Also, if you use a Windows emulator (Fusion, Parallels, VirtualBox) to open your Bootcamp partition instead of booting from it, you can use BTT.

**Comment by tigerpa666666** [comment]
Thank you very much!
    I have tried the Extramagic,but the software is not better than BTT,and when using in the VMware the BTT,The BTT can not control each Windows software alone, except in Unity mode.
    So my advice is create a kind of BTT to use in Bootcamp .

        
.

**Comment by jeffmann** [comment]
That might be nice, but it would have to be Windows software. It's probably not something that Andreas would make..? It's also not so easy. People were asking for many years for Extramagic to be made by the Trackpad++ developer, before he could make it work. Maybe you can suggest to him the changes you would like.

**Comment by fifafu** [comment]
Yeah it's complicated because on windows there is no API to get the touchpad touches. The developer of Trackpad++ needs to do some pretty hard hacks to make it work. This is a lot of work and very complicated.

BTT definitely will never be available for Windows. Trackpad++/Extramagic are definitely the best options available currently. (And I doubt this will ever change)

**Comment by tigerpa666666** [comment]
Thank your explanation,maybe  I think this  problem is too simple. whatever I will support  the BTT’s develop .

I will tell you the  BTT’s problem when  I  use it.

Thanks again!
