### ISSUE TITLE
Global action for "Activate Currently Hovered App in Dock" does not take precendence over other apps

### ISSUE THREAD

**Issue by proactivematter** [fifafu/BetterTouchTool#2144]
Hello!

I have set three-finger-click to "Activate Currently Hovered App in Dock" and then CMD+Q under GLOBAL (one of my favorite implementations so far!).

But it seems that if focus is on an app that already has some other action assigned to three-finger-click, it won't work on the first try..!

I tried setting the gesture for the app to only work when "Cursor isn't touching the dock or menubar", but the results were the same.

Am I missing something?

Thank you!

Type of Mac: Macbook Pro 15" 2017
macOS version: 10.13.3
BetterTouchTool version: 2.340 (719)

**Comment by fifafu** [comment]
Application specific settings are always triggered first. Only if no appropriate application specific setting has been found the global setting is triggered. This is part of the fundamental logic in BTT.

However you seem to have found a bug, because after enabling the "Cursor isn't touching the dock or menubar" this should be working like you want it to work. I'll check whats wrong!

**Comment by fifafu** [comment]
This should now be working in 2.345 alpha

**Comment by proactivematter** [comment]
Wow! So quick! Thank you so much Andreas! I'm not on alpha (prefer to wait for stable releases) but I'll let you know how it works out once once I get it.

**Comment by proactivematter** [comment]
Solved in v2.402 (753)! Thank you @fifafu !
