### ISSUE TITLE
[feature request] Do not run Touch Bar scripts on machine without Touch Bar

### ISSUE THREAD

**Issue by merlinND** [fifafu/BetterTouchTool#2193]
#### Description of bug/feature request/question:

**Feature request**: on machines without TouchBar, do not run TouchBar scripts even if some are configured.
This situation easily happens when syncing settings between multiple machines, but only one has a Touch Bar. 

Especially because of high CPU usage and effect on battery life (issue #2174), it would be really great to either be able to disable Touch Bar buttons with machine-specific (not synced) checkboxes; or automatically ignore them when Touch Bar is not available.

#### Device information:

Type of Mac: MacBook Pro (on with and one without Touch Bar)
macOS version: 10.13.3
BetterTouchTool version: 2.340

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar / lack of Touch bar.

**Comment by fifafu** [comment]
The problem is that there are people who use virtual touch bars thus I can't just disable it completely.

However there is a way to do this. In the "Other tab" in BTT is a action "Run after launching on Mac with Serialnumber". If you use that action and enter your Mac's Serial (can be found by clicking the Apple icon in the menubar => About this Mac) you can assign the "Switch to Preset" action. 

Now if you put your touchbar settings in a separate preset you can easily disable/enable it like this.

![image](https://user-images.githubusercontent.com/8820811/37083142-e82b272a-21ee-11e8-9640-e9dde4f8a15c.png)
![image](https://user-images.githubusercontent.com/8820811/37083164-feed91a0-21ee-11e8-93cc-4de36ddca34d.png)

**Comment by merlinND** [comment]
The combination of presets + "switch to preset" action is super powerful, I had never realized! Thanks for pointing it out.
This could be added to the Knowledge base :)

**Comment by merlinND** [comment]
Quick follow-up question: what's the best way to move existing TouchBar actions / widgets to a different preset? I've [looked up the documentation](https://docs.bettertouchtool.net/docs/preferences_presets.html) and tried the export / import features, with no luck. It seems that TouchBar actions are not part of what's being exported.

**Comment by fifafu** [comment]
In general exporting & importing should work fine.
If that doesn't work, could you go to the about tab in BTT and click the "Export Debug Information" button? This will create a folder called BetterTouchToolDebug on your Desktop - if you send that to me (boastr.net@gmail.com) I'll check why it's not exporting the Touch Bar stuff. Maybe that's a bug.

**Comment by fifafu** [comment]
I think the preset export should now work with v2.366 alpha

**Comment by merlinND** [comment]
It does! Glad the debug info could help.
Thanks again for your reactivity.
