### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by Sinetempore** [fifafu/BetterTouchTool#2278]
Shortcuts do not work in any app, they just bring up the menu.
To make it work you need to press shortcut twice.

**Comment by mark-bamberg-medfx** [comment]
I think I am also seeing this issue with version 2.412.  My previous working context-menu shortcut actions are not working.

I have a sequence of context-menu actions associated to a keyboard shortcut.  This was working until recently.  Now no.

**Comment by fifafu** [comment]
If possible please try v2.414 alpha, I have made some little changes - it seems there has been a change in how macOS handles context menus recently.

**Comment by fifafu** [comment]
@mark ah, I believe this was a different problem :-)
Could you try v2.415?

**Comment by mark-bamberg-medfx** [comment]
That fixed it; thank so much!
 
Harriscomputer










Mark Bamberg
Director, R&D
P: 800.421.9497
Support number: 800.466.1438






150 Lavan Street
Warwick, Rhode Island
02888
www.medfx.com










This message has been sent on behalf of a company that is part of the Harris Operating Group of Constellation Software Inc. These companies are listed
here.
If you prefer not to be contacted by Harris Operating Group 
please notify us.

This message is intended exclusively for the individual or entity to which it is addressed. This communication may contain information that is proprietary, privileged or confidential or otherwise legally exempt from disclosure. If you are not the named addressee,
 you are not authorized to read, print, retain, copy or disseminate this message or any part of it. If you have received this message in error, please notify the sender immediately by e-mail and delete all copies of the message.
