### ISSUE TITLE
Not responding message from CleanMyMac 3

### ISSUE THREAD

**Issue by einarso** [fifafu/BetterTouchTool#2313]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I regularly get a message from CMM3 that BTT is non responsive.

#### Device information:

Type of Mac: Macbook Pro 2017
macOS version: High Sierra
BetterTouchTool version:  2.405

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

<img width="334" alt="screen shot 2018-03-23 at 08 48 00" src="https://user-images.githubusercontent.com/18497512/37817609-a4da6aae-2e77-11e8-88ce-c238cfbe775a.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Is BTT actually unresponsive of is the message wrong?

**Comment by einarso** [comment]
Most times the message is wrong.  But there have been cases where I need to restart BTT.

**Comment by fifafu** [comment]
Restart via the BetterTouchTool menu? (if so - BTT is not unresponsive, otherwise the menu wouldn't show up). Only if there is a beachball icon while hovering the BTT icon it is really unresponsive (which may be normal for max 2 seconds in some situations)

I'd just tell CleanMyMac to ignore this. BTT is sometimes using "delays" to make some actions work correctly, CleanMyMac may interpret these delays as "non-responsiveness".
