### ISSUE TITLE
[Feature Request] Reverse shortcuts' creation order

### ISSUE THREAD

**Issue by waxfingers** [fifafu/BetterTouchTool#2318]
Instead of having to scroll to the end to add/edit a shortcut, there could be a toggle (or even better some setting/menu checkbox) that displayed the shortcuts by creation date in reverse order, this is top to bottom from newer to older . It would be neat if BTT could "remember" this setting so there would be no need to activate it each time its preferences window is called... well also the window position (but though related that's another mater). Thank you =)

**Comment by fifafu** [comment]
Unfortunately this would break drag & drop reordering within the table.
I currently don't really plan to make this available in the current UI because it would also make the logic to reorder child actions more complicated.

However I'm already working on a big overhaul of the UI and will put this on the Wishlist :-)
