### ISSUE TITLE
Shortcut does not bring chrome in the front, but create a new tab in the background

### ISSUE THREAD

**Issue by zfdang** [fifafu/BetterTouchTool#2326]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I used to have "shortcut" to launch google chrome. Chrome will be opened if not, and Chrome will be brought to the front if opened already. But now when the shortcut was pressed, one new tab was created in chrome, but chrome was not brought to the front.

#### Device information:

Type of Mac:MBP 13"
macOS version: 10.13.3
BetterTouchTool version: 2.405

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Chortcut, assigned action: "Launch Google Chrome.app"

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by OrbitalTech** [comment]
Temporary fix:
<img width="380" alt="screen shot 2018-03-26 at 6 24 27 pm" src="https://user-images.githubusercontent.com/23006558/37888276-f3437bc4-3122-11e8-9fcd-d929c042b1bc.png">
Set your button to run applescript. Then enter the following line. Should do the trick.

`activate application "Google Chrome"`

I fear this may be a change in Google Chrome rather than a bug in the latest version of BetterTouchTool.

**Comment by fifafu** [comment]
Jup, that's a change in the newer Google Chrome versions and not related to BTT.
@OrbitalTech's workaround should work fine.
