### ISSUE TITLE
Type/paste custom text not fully functional

### ISSUE THREAD

**Issue by mijalche** [fifafu/BetterTouchTool#2351]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

When I press a key sequence (hh) in my email app (Spark) the following text should be typed

Hello ,

Best regards

When the text is typed, the cursor should return before ,

However, the following is typed
Hello , Best Regards

The problematic behaviour I recognised is: the cursor is returned before the text is typed and enter is ~~not recognised~~ typed after the text has been typed.

Keep the good work. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard shortcuts

#### Device information:

Type of Mac: Macbook Airearly 2014
macOS version: 10.13.3
BetterTouchTool version: 2.422

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by waxfingers** [comment]
I tried to reproduce your example and:
Given a text 

> Hello ,  
> Best regards


- If in BTT I select **insert text by pasting** (instead of typing)
- If in the sequence properties I mark the **delete typed characters** checkbox...and insert a value of **2**

The text is pasted perfectly formatted.

Now, if I also wanted the cursor to go right before the coma, an UU (ultra-ugly) but fast fix that comes to mind is to use and additional action with applescript (I'm just a copy paste robot, not a coder :P). Something like

`tell application "System Events" to tell process "Spark"`
	`key code 123 & 123 & 123 & 123 & 123 & 123 & 123 & 123 & 123 & 123 & 123 & 123 & 123 & 123 & 123`
`end tell`

**Comment by fifafu** [comment]
I can reproduce the issue when using the "typing" option. Will be fixed in the next alpha in about an hour.

**Comment by fifafu** [comment]
Could you test v 2.423 alpha? (get via check for alpha version updates")

**Comment by mijalche** [comment]
2.423 solves the issue. Thanks!
@waxfingers thank you for the solution. It inspires me to play with applescript
