### ISSUE TITLE
3 finger swipes do not work on BTT Remote.

### ISSUE THREAD

**Issue by moshed** [fifafu/BetterTouchTool#245]
macOS 10.12.2 (16C67)
MacBook Pro (Retina, 13-inch, Mid 2014)
BTT 1.984

it seems the fault is in the app though, which does not recognize three fingers. there are only round circles around 2 of my fingers .

**Comment by fifafu** [comment]
Sorry for not reacting earlier.
However this seems to work fine on all my iOS devices. Which kind of device were you using?

I think there was some accessibility setting in iOS that consumed three finger gestures and prevented them from being sent to apps. Do you have any Accessibility settings enabled?

I'm closing here for now because this issue is quite old, if you are still interested, please comment.
