### ISSUE TITLE
Feature Request - Proper Handling of Spaces

### ISSUE THREAD

**Issue by pallavmac** [fifafu/BetterTouchTool#281]
#### Description of your feature request:
One of the most annoying functions of MacOS is the automatic rearrangement of the spaces. These work really badly. I know I can turn this off. But there's one BIG problem with that. Every time I make an app fullscreen, MacOS puts that full screen window on the last spaces! I was wondering wether you could use your amazing coding skills to have an awesome option that would place the app that is made fullscreen, to the right of the current desktop. 

If not possible. Then you can close the thread. Just was hoping this extremely irritating feature could be fixed.

**Comment by fifafu** [comment]
Unfortunately I'm not sure if this is possible. I think there might be other tools more suitable for such an option, because I think it would be a lot of work to integrate it into BTT (if it's even possible).

https://totalspaces.binaryage.com/ requires you to disable System Integrity Protection but maybe it could do something like this.
