### ISSUE TITLE
Feature request: map keyboard shortcuts to Wacom tablet ExpressKeys

### ISSUE THREAD

**Issue by mamabox** [fifafu/BetterTouchTool#293]
It would be *amazing* to be able to map keyboard shortcuts to Wacom tablet's ExpressKeys (especially Display Toggle). Thank you for considering!

**Comment by fifafu** [comment]
Unfortunately I don't think I'll be able to add this.

Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.
