### ISSUE TITLE
Bug: Don't work "Trigger on key down" option

### ISSUE THREAD

**Issue by xpert13** [fifafu/BetterTouchTool#376]
#### Description of your bug/question/feature request...:

When I try to activate "Trigger on key down" option for any of my shortcuts it doesn't work at all.

**What kind of Mac are you using?**

iMac (late 2015)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Logitech keyboard

**Which versions of macOS and BetterTouchTool are you running?**

macOS Sierra and BetterTouchTool 2.02 (in the previous versions this function doesn't work too)

**Comment by fifafu** [comment]
There are certain keys it currently can't work with (mostly the arrow keys). Normal keys should however work fine.

**Comment by xpert13** [comment]
I was trying to activate it for Ctrl+Z

**Comment by fifafu** [comment]
mhm that should definitely work, which version of macOS are you running?

**Comment by xpert13** [comment]
macOS Sierra 10.12.3 (16D32)

But I was trying to activate this function last 2 month. When I activate it the shortcut stop working.

**Comment by CaptainCapstone** [comment]
I am having a similar issues.  I have a keyboard gesture enabled for a specific app (tn3270 X), that modifies the behavior of the delete key.  I am using the macbook keyboard, nothing external.  My shortcut works when triggering on key up, the operation of the delete key works as specified.  When I enable trigger on key down, the shortcut is no longer functional.  I was hoping to enable the repeat function, but alas, those hopes were dashed.

Shortcut is **Delete**.  Assigned Action is to trigger other keyboard shortcut **Command-Delete** with Additional Action to trigger other keyboard shortcut  **Delete**.  (Makes it work like a backspace, woohoo)

Otherwise, thank you very much for this great app.

Better Touch Tool Version: 2.071
macOS Sierra Version 10.12.3
MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by fifafu** [comment]
@CaptainCapstone are you using the internal keyboard or an external one?

**Comment by CaptainCapstone** [comment]
Internal Keyboard.  I tried with an Apple external keyboard as well.  Same results.  I also had a coworker with a MacBook Pro try, and he also saw the same thing.  Nothing happens with "trigger on key down" selected.

**Comment by fifafu** [comment]
Does this still happen with the current BTT versions?

**Comment by xpert13** [comment]
Yes. Nothing changed.

**Comment by fifafu** [comment]
Mh what kind of shortcut/action combinations are you trying? (I have tested on multiple systems and it seems to be working fine here, at least on 10.13.x - maybe I'm missing something)

If possible, it would be great if you could go to the about tab in BTT and click the "export debug information button". This will create a folder called BetterTouchToolDebug on your desktop. It would probably be very helpful if you could send it to boastr.net@gmail.com (and reference this issue)

**Comment by xpert13** [comment]
I trying to use it for Ctrl+Z -> Command+Z  shortcut.

Debug information was sent via email.

**Comment by fifafu** [comment]
Could you try the new alpha? (2.333) I made some changes, maybe this is now working for you.

**Comment by xpert13** [comment]
"Trigger on key down" is work now (in previous version after activation this setting shortcut didn't work at all). But "Repeat action while shortcut is pressed" still not working.

**Comment by fifafu** [comment]
@xpert13 indeed! That was more complicated to fix than expected but I think I found a solution. Will be available with the next alpha tomorrow.
