### ISSUE TITLE
Cannot replicate mouse key functionality with a keyboard key

### ISSUE THREAD

**Issue by jhimanka** [fifafu/BetterTouchTool#384]
#### Description of your bug/question/feature request...:
I used to use Karabiner to remap left control key to work as a left mouse button. Everything worked: clicking, selecting text etc. Karabiner broke for Sierra and I'm looking for an alternative. 

I can get the left click working with the control key but not selecting and dragging. Is there a way to make it work?

**What kind of Mac are you using?**
2012 Macbook Pro Retina 15"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Internal keyboard and Matias Compact Tactile 

**Which versions of macOS and BetterTouchTool are you running?**
macOS Sierra, up to date, latest BTT

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.

BTT doesn't allow to do this with just modifier keys yet, you would need to combine it with a normal key like this:
![image](https://user-images.githubusercontent.com/8820811/38379676-bbefd3c0-3901-11e8-83ab-f88758890204.png)

However I think Karabiner in the meantime also has been fixed to work on High Sierra.
