### ISSUE TITLE
BTT constantly asks for accessibility API permissions, even if it doesn't need them

### ISSUE THREAD

**Issue by Zalathar** [fifafu/BetterTouchTool#41]
#### Description of your bug/question/feature request...:

I have BTT configured to do everything I want it to do, and none of those features require access to the system's accessibility APIs.

However, every time I open my laptop, a message from BTT appears in the middle of the screen asking for accessibility permissions that it doesn't actually need.

There doesn't appear to be any way to prevent this popup from appearing.

**What kind of Mac are you using?**

MacBook Pro (Retina, 13-inch, Early 2015)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which version of macOS are you running?**

macOS Sierra 10.12.1 (16B2657)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Ideally BTT should be displaying these unnecessary popups at all. Failing that, there should be some way to prevent them from appearing *without* granting accessibility API access.

<img width="527" alt="screen shot 2016-12-07 at 7 41 30 pm" src="https://cloud.githubusercontent.com/assets/20290842/20960567/2f0b9eae-bcb5-11e6-87af-b7b570efee92.png">

**Comment by fifafu** [comment]
Sorry, BTT just need those permissions. 
In older versions it was possible to ignore the message, however that lead to sooo much wasted time trying to find bugs that people reported that eventually turned out to be caused by the missing permissions.

The whole code base assumes this API is available and it leads to hundreds of little issues if it's not enabled. (E.g. Tip Taps won't work correctly, capturing keyboard shortcuts won't work correctly, random crashes can occur and much more).

Unfortunately I really can not support BTT if that API is not enabled.
