### ISSUE TITLE
Mouse actions do not work when VNC to Mac from iPad

### ISSUE THREAD

**Issue by pruppert** [fifafu/BetterTouchTool#417]
I am VNC'ing into a 2012 MacBook Pro from a 9.7 iPad Pro via the JumpDesktop iPad app which supports use of a Citrix X1 mouse. The mouse works fine for interacting with macOS in the VNC session, and mouse clicks are correctly identified in the "Click here to select mouse button" window in BTT.  However, no actions actually get triggered by mouse clicks. Any idea what the problem is here? Have others had problems with using BTT in a VNC session?

This is BTTT 2.02 on macOS 10.12.3.

Edit to add that window snapping, resizing, and moving actions also do not work.

**Comment by fifafu** [comment]
Unfortunately the events generated by the VNC client are probably missing some things BTT needs to work.

There are various such issues already open with Remote Desktop software like VNC or Microsofts. #121, #215.

I don't think this can be fixed in BTT, but I'm tracking it and will soon check what exactly is causing it.
