### ISSUE TITLE
Turning off Force Touchpad features on BTT while keeping all else?

### ISSUE THREAD

**Issue by DavidbivaD** [fifafu/BetterTouchTool#449]
Hey,

I was wondering if there was a way to turn off all the force touchpad features on BTT and just let the system do its thing, while still using BTT for other things that I like such as keyboard shortcuts and regular trackpad gestures?

I'm on a 2015 5k iMac, using the Magic Trackpad 2. Mac OS X 10.11.6 with BTT 2.04.

I cannot get the settings for force touchpad to match the system pressure and feedback and it's bothering me like crazy. None of the options in BTT feel exactly like the default Mac's clicks. 

I still use a ton of the BTT keyboard shortcuts and a couple regular trackpad gestures, so I was hoping there was a way to just turn off the Force Touchpad section and keep everything else. 

Is there a way to do this at all?

**Comment by fifafu** [comment]
Well, if you don't add any gestures that require clicks, BTT shouldn't interfere with any system force touch settings. What exactly is causing problems for you?

**Comment by DavidbivaD** [comment]
Basically, I've been using the 3 finger click since the original magic trackpad as a CMD+click shortcut. It's just that when I do that shortcut, because I can't match the BTT settings to be exactly or at least super close to the system's click feel, it's feels super jarring every time I use that shortcut. 

So I was basically wondering if there was a way to have the gesture on, but just leave the force touch feedback to the system's default.

But I guess since everything is software based, in order to have the gesture BTT has to take over the click feedback as well?

**Comment by fifafu** [comment]
Ah now I see.
Unfortunately I haven't found a way to do this reliably because I don't know when the system thinks the click treshold has been reached. In BTT I need to specify my own metrics to determine when that treshold has been reached because Apple doesn't  provide an API for that. So if I don't disable the default system three finger click it always triggers the haptic feedback a little bit before or after BTT triggers the assigned action, which is very confusing.

I'll try to work on the haptic feedback to better match the Apple behavior, but unfortunately it's very complicated because it's all inofficial API without any documentation...
