### ISSUE TITLE
Snap mouse to active buttons

### ISSUE THREAD

**Issue by gsab2** [fifafu/BetterTouchTool#458]
#### Description of your bug/question/feature request...:

I'd be very interested to know if you plan to add a feature to snap the mouse pointer to active buttons

**What kind of Mac are you using?**
Mac book air

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
**Mouse**

**Which versions of macOS and BetterTouchTool are you running?**
El Capitain

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by Sergesouszero** [comment]
The "snap to" function is one the **rare** advantage of using Windows over macOS. LazyMouse did that, but it hasn’t been updated for a while and is not compatible anymore with more recent OS like El Capitan or Sierra. You could always use SteerMouse, but you’re gonna have to pay 20$ only for that function (the other functions are not compatible with the Magic Mouse). I’m pretty sure that adding this feature in BetterTouchToll would make a lot of users happy. :)

**Comment by gsab2** [comment]
I completely agree. It would be do useful. Can't stomach $20 for that one
feature.

-- 
Glen Saberton

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.

With recent alphas you can use the move mouse to position action relative to the default or cancel button:
![image](https://user-images.githubusercontent.com/8820811/38382158-5b7b64e8-3909-11e8-9f87-b50b084e5b04.png)
However BTT doesn't continuously scan for changed buttons (as that has quite a performance overhead). So you would need to assign that "move mouse to position" action to some trigger.

**Comment by Sergesouszero** [comment]
Hi Andreas,

I had completely forgotten about this.Thank you very much for your reply.

Best regards,

Serge Tanguay - Montréal‌‌‌
‌‌
