### ISSUE TITLE
Possible to show buttons on app pop-up windows?

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#459]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
Is it possible for you to detect pop-up windows within an app and present a new touch bar with the buttons that are on that window (like OK and Cancel)?  If so, it would be a good option to make this possible.  It would be make the touch bar much more useful in apps that don't directly support the touch bar.

**What kind of Mac are you using?**
2016 MacBook Pro 13:

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**
10.12.3 and 2.04

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.

AFAIK this feature would require constantly monitoring an app using the accessibility api, which has quite an performance overhead. I currently don't think I'll add this to BTT.
