### ISSUE TITLE
Two finger tap inoperative

### ISSUE THREAD

**Issue by mrdampsquid** [fifafu/BetterTouchTool#469]
#### Description of your bug/question/feature request...:
Two finger single tap works less than 50% of the time.

**What kind of Mac are you using?**
MacBook Pro 15" mid '15

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Magic Mouse

**Which versions of macOS and BetterTouchTool are you running?**
Currently 10.12.3 & 2.04  This issue has been around for ~ 2 years now.

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
Sometimes it works, sometimes it doesn't.  Sometimes an isolated tap will suddenly work, sometimes it works multiple times in a row.  Usually it doesn't work multiple times in a row.  Doesn't seem to matter whether finder is active, or depend on a particular app.  Can't discern an pattern.  Restarting BTT makes no difference.  Watching Live View it's the same, sometimes the action is registered, sometimes not.  No pattern there either.

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.

I can't seem to reproduce this issue (at least not with recent versions)
