### ISSUE TITLE
set startup config file

### ISSUE THREAD

**Issue by jeremybundgaard** [fifafu/BetterTouchTool#485]
Most important app for my UI! Love this app!

Allow us to set which config file at start...that way we can sync with cloud drive

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.

Unfortunately the config file location is fixed. You can however use Dropbox sync in the advanced preferences.
