### ISSUE TITLE
Please make keyboard binds compatible with KVM software

### ISSUE THREAD

**Issue by ChesterYHo** [fifafu/BetterTouchTool#491]
#### Please give us an option to have BTT emulate an external keyboard for text binds

**Macbook Pro mid-2010**

**Magic Trackpad**

**macOS sierra**

 I use KVM software so that I can easily use switch between a Mac and PC while using the same peripherals, and I like to map keyboard shortcuts to gestures with BTT. However, when I switch over to controlling my PC, the keyboard shortcuts are not sent over to my PC. Instead, they still get inputed back at the Mac.

For example, I set two fingers swipe up to enter Control (not Command) + t, to open a new tab on my Windows machine, however when I swipe up while controlling my PC, a new tab doesn't open, instead, a "t" gets typed in on whatever window is active on the Mac.

So it seems that BTT "injects" the text directly into whatever application is open on the Mac. This is putting a huge wedge in my workflow.

So, what I would really like is if there could be an option to have BTT input text by emulating a keyboard inputting the text instead of directly injecting the text in. This way, the text should be picked up by the KVM software and therefore allow me to use my gestures with my PC.

Is this possible? I'd greatly appreciate it if this could be done. Again a lot of my workflow is reliant on this, I'd really hate to give up the usefulness of gestures, and I'm sure that I'm not the only one that is using a KVM.

Please consider adding this feature to make BTT so much more useful for those of us who use KVMs. Thanks!

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.

You can try to enable compatibility mode for this KVM software, if that doesn't work I won't be able to add it to BTT unfortunately (as this is the lowest level BTT can go)
