### ISSUE TITLE
Touchbar Custom Keyboard Commands only partially fixed in 2.071--Use Case Provided

### ISSUE THREAD

**Issue by rwross1776** [fifafu/BetterTouchTool#505]
The lock, empty trash, etc functions that weren't working in 2.07 seem now to work when using predefined actions, however custom keyboard shortcuts only seem to work in limited situations.  I am unclear whether this is a bug or a limitation.

Use Case:
Global Touchbar button made to empty trash (could be anything though) SHFT CMD Del
Function ONLY works if Finder is in focus. With any other app in focus, the button does not fire.

However, if a predefined action is used to empty trash, the function fires regardless of what app has focus.

The question is why do Custom Keyboard Shortcuts and Predefined Actions function in different ways and is this a bug or a limitation.

**Comment by fifafu** [comment]
Well it's neither a bug nor a real limitation, it's just how things work :-)
The empty trash shortcut only works while Finder is active (even if you press it manually on your keyboard) because it is a Finder shortcut. Other apps could use that shortcut for different things.
When sending keyboard shortcuts BTT does exactly the same as when you press that shortcut manually on your keyboard.

This is why BTT offers the additional "empty trash" action which works in any app but uses a very different mechanism to achieve this.

You can always use the "Send shortcut to specific application" predefined action if you want to trigger a shortcut in a specific app.
