### ISSUE TITLE
Keyboard shortcuts change according to current input language

### ISSUE THREAD

**Issue by megema** [fifafu/BetterTouchTool#518]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
If I set a keyboard shortcut for an action, or set a mouse button to trigger a shortcut, BTT saves the id of the keys, not the character they currently represent. It's an issue, because applications' shortcuts depend on the displayed language, not the input language. So, when I set a mouse button to trigger CMD+[ (Back) and then change the input language to Hungarian, this shortcut becomes CMD+Ő and it will not work. If I override it in System Preferences, it's working, but then it won't with US input.

Also, there aren't any predefined action in BTT for "Back" and "Forward".

**What kind of Mac are you using?**
rMBP 13" 2013 Late

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Magic Keyboard, Normal Mice (Logitech MX620)

**Which versions of macOS and BetterTouchTool are you running?**
macOS 10.12.3, BTT 2.0.4

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by z4y4ts** [comment]
I'm having the same issue.

@megema just figured a workaround for these specific hotkeys. You can use `⌘⌥←` & `⌘⌥→` instead of `⌘⇧[` & `⌘⇧]`. This works for me in Google Chrome and Sublime Text.

**Comment by henri-tremblay** [comment]
I have what is probably a related problem. Cmd+` should switch window on a US keyboard. When I switch to Canadian French, the same key is ù. So I tried to map Cmd+ù to the same thing with BTT. So the same key should switch window in both languages. But if I record Cmd+ù, when switching the keyboard to US, BTT will magically change the shortcut to Cmd+`.

Bottom, I'm not able to map Cmd+ù to the window switch.

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or encounter problems, please create a new issue - I'm now much more responsive than a few months ago.

Unfortunately there is no solution to this. You could create different presets for each layout (I know this is not a very good workaround, but I can't handle this in BTT as the APIs provided by the system always save the keycode, which describes the physical position of the key on the keyboard and not it's assigned character)
