### ISSUE TITLE
[FEATURE] Built-in library of drawing gestures

### ISSUE THREAD

**Issue by SteveJobzniak** [fifafu/BetterTouchTool#549]
One of the things severely lacking in BTT is a library of default gestures that people can use without having to train BTT. Training is great for complex things. But newbies just want something that works immediately.

The best library I've ever seen was from https://www.jitouch.com/characters/ (before I switched back to BTT). Go to that page and click the button that says "Show Gestures: All".

You can hover over the images to see animations showing how to draw them.

It includes the whole alphabet from A-Z, Up, Down, Left, Right, Left-Right, Right-Left, Up-Left, Up-Right, Left-Up, Right-Up, / Up, / Down, \ Up, \ Down.

And all of their gestures have been trained on multiple ways to draw them, so the detection accuracy is incredible. It was really an effortless product. BTT does more things overall. But right now it doesn't hold a candle to Jitouch's drawing engine and library of gestures.

I've manually duplicated them in BTT, but other people aren't as lucky. It would be great if BTT one day had a library of gestures. And these ones may give you some great inspiration, Andreas! :-)

**Comment by fifafu** [comment]
Hey,

I'm sorry, but it has always been a fundamental believe of mine that BTT should not include any defaults because there are so many different users and different use cases and I don't want to influence them.  This has worked really well for me  and will definitely not change.

**However** I'm working on a competely new export/import system and a platform where users can share their setups. This will probably be a good and very powerful  replacement for an integrated library :-)
