### ISSUE TITLE
Custom colors in Touchbar?

### ISSUE THREAD

**Issue by Plcd22** [fifafu/BetterTouchTool#561]
I am in my trial period right now, but I can't seem to find one thing that will make me purchase this pretty sweet tool.
Is there a way to assign custom colors to the touchbar? I type a couple documents in pages every week and I have about a half dozen colors that I use on EVERY doc I make, right now I have to go through the color picker and select the colors that I have saved from there. The built in touchbar gives quick color options but it is just the default colors and they are not the ones that I use. I came across this BetterTouch because I was looking for a way to customize the colors that I can quickly access on the touchbar.
Thank you for your time,
Loren

**Comment by cleverjackal** [comment]
What if you added custom colors to the color picker tool in the app you're trying to type in? I can't try it out because I don't have a Touch Bar Mac.

**Comment by Plcd22** [comment]
Hello Cleverjackal,
Already did, that's how I use them all the time but they don't show up on the touchbar.  Only the default colors do, and a couple variations but not the ones I need/use.  
I'm using Pages on a MacBook Pro 13" with touchbar (late 2016)

**Comment by fifafu** [comment]
Hey,

I'm sorry but I think this won't be possible with BTT. The problem is that all applications implement how they react to color changes differently. There might be some hacky solution using Apple Script, but it would be different for every application and not even possible for most.

In textedit something like this would apparently work to change the selected color, but it would be different for Pages:

```activate application "TextEdit"
tell application "System Events" to tell text area 1 of scroll area 1 of window 1 of process "TextEdit" to if exists then
	set {x, y} to value of attribute "AXSelectedTextRange"
	if x ≤ y then tell application "TextEdit" to set color of document 1's characters x thru y to {0, 0, 65535}
end if
```

**Comment by cleverjackal** [comment]
You could also create a multi-gesture with BTT as well I guess. You know, click here, and then click here, and then type this string and whatnot.

**Comment by SteveJobzniak** [comment]
@Plcd22 BetterTouchTool has a "Run AppleScript" action. So my first thought was to look there. And yes turns out it's possible to set text colors of selected text via AppleScript, but it seems complex and app-specific so some research would have to be made.

Pages 5+ seems to have removed the "get the selection" AppleScript command. At least I cannot find any way to affect the selected text... Here is how far I got for you:

```applescript
set colorRed to {64638, 4079, 6844}

tell application "Pages" to tell front document to tell body text
	set the color of the first word to colorRed
end tell
```

**Comment by Plcd22** [comment]
Thanks for all your help but it appears that without getting more technical than I can, it seems to be out of my reach!  Again thanks for your answers and tips
