### ISSUE TITLE
How do I disable the red dot whenever I right-click?

### ISSUE THREAD

**Issue by danielhaskett** [fifafu/BetterTouchTool#594]
Hello!

I am working on a ---

**MacBook Pro (Retina, 13-inch, Late 2013)**

with a 

**Wacom Bamboo Trackpad**

and using 

**Mac OSX Sierra
Better Touch Tool 2.071**

Whenever I **right click** I always get a **red dot** appearing that then sends my current Photoshop window into my second screen. 

I'd just like to **disable** this red dot feature as I really **don't** need it.

Any help much appreciated!

Thanks so much,

Dan

**Comment by cleverjackal** [comment]
Are you sure this is BTT? I've never seen red dots on it.

**Comment by danielhaskett** [comment]
Yeah I am sure...whenever i disable BTT it stops happening

**Comment by fifafu** [comment]
Hi Daniel,

you have probably configured one or multiple drawing gestures. Since the last bigger update BTT supports right-mouse drawing, however it should only begin to draw if the mouse is moved while the right button is being held down.

You can either disable right mouse drawing completely or disable the highlighting of the start-point, see this screenshot:
![image](https://cloud.githubusercontent.com/assets/8820811/23525924/718e0348-ff90-11e6-9f15-a5ee167fe48c.png)

**Comment by danielhaskett** [comment]
Amazing, that worked perfectly. Thanks a lot for your help Fifafu!
