### ISSUE TITLE
Left click sometimes doesn't work

### ISSUE THREAD

**Issue by Calpicow** [fifafu/BetterTouchTool#625]
#### Description of bug/feature request/question:
Left click does not always register when BTT is running.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad + External USB Mouse

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2014)
macOS version: 10.11.6
BetterTouchTool version: 2.071 (608)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Quitting or disabling BTT fixes the issue. Disabling BTT for Finder also works.

**Comment by Rzah** [comment]
Also have this issue, left click not working reliably after BTT has been running for ~10hrs, disable/enable gets it working again. 10.11.6 2.071 (608) Magic Trackpad.

Not seeing anything in the console log, issue appeared to occur suddenly today (rather than a slow degradation)

**Comment by BioExorzist** [comment]
Me too, but from the first second after BTT has been startet.
I use BTT to configure additional Buttons from my Razer Deathadder Mouse.

And the Update to Version 2.071, didn't change the problem...

**Comment by kritua** [comment]
Same here - BTT ignores single click right after start. Pretty annoying thing.

**Comment by Rzah** [comment]
Resolved for me on version 220 (641)

**Comment by kritua** [comment]
I've tried 2.20 and even 2.23 alpha. Single click still os not working properly

**Comment by fifafu** [comment]
@kritua in that case you are probably using a gesture that needs to block clicks in certain situations. The most common ones are corner clicks. Try to remove them if possible.

**Comment by kritua** [comment]
I'm not using corner clicks at all. TipTap Left, Right, 3 finger tap and 4 finger tap.

**Comment by drhumlen** [comment]
Wow! Is _this_ what's causing my left-click ("shoot button") in games to not work from time to time? Holy moly! I was so close to returning my mouse back to the store with great fury! It was only the other day I noticed that my hand being closer to the touchpad affected the duration of it. (The 2017 MBPs have a way too huge trackpad)

Don't get me wrong, BTT is the best app I have. It's the very first thing I'd install on a fresh machine, but omg this has killed me 1000s of times in games because my shoot button has stopped working. Funnily enough, disabling the touchpad when an external mouse is connected (Accessability Settings) doesn't change that. So even though the touchpad is completely disabled, BTT still eats the leftclick events from my external mouse. No wonder I thought it was the mouse that was the problem.

**Comment by danielywang** [comment]
Same here! My left click works in inconsistently when BTT is open. Please fix this...
