### ISSUE TITLE
[FEATURE REQUEST] Calling Applescripts/ Triggers

### ISSUE THREAD

**Issue by Element2io** [fifafu/BetterTouchTool#651]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Currently the only way to run apple scripts automatically for the touchbar is through a loop which we can execute every x seconds. 

My suggestion is that we add some integration with system wide changes as a trigger to run the apple script. Or the ability for an apple script to call up the function within BTT.  So say we want to update the local IP address and display it on the touchbar. 

- If wifi network changes then updatetouchbar display 
 
It would be really nice to have another way to trigger the apple scripts within BTT.

Didn't have much time to write this, so I hope it makes sense. Thanks, and great work!

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by cleverjackal** [comment]
It would be cool with BTT, but for now you can do it with ControlPlane. I'm sure fififu has a lot of work right now!

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or still encounter this problem, please create a new issue - I'm now much more responsive than a few months ago.

In the latest alpha version it is possible to trigger the script assigned to a TouchBar widget using Apple Script or a custom URL. You can also provide new content to the widget if wanted.
See https://updates.bettertouchtool.net/alpharls.html
