### ISSUE TITLE
Trackpad clicks not always recognized

### ISSUE THREAD

**Issue by fitzage** [fifafu/BetterTouchTool#667]
#### Description of bug/feature request/question:

Not sure if this is related to the update I installed today, but my force touch trackpad frequently doesn't register clicks with BTT enabled. Quitting BTT seems to fix the problem. It returns after having BTT open for a bit. I can't state with 100% certainty that BTT is the problem, but it seems like it in my testing. I don't have any of the trackpad based features in BTT set up, as I'm just using it for Touch Bar customization.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro Trackpad

#### Device information:

Type of Mac: MacBook Pro 2016 13" TouchBar
macOS version: 10.12.3
BetterTouchTool version: 2.083 (613)

**Comment by sdrygalski** [comment]
I have the same problem.

I think it can have something to do with this issue and how it was solved: https://github.com/fifafu/BetterTouchTool/issues/191#issuecomment-289279886

**Comment by fitzage** [comment]
I've been thinking about this, and I haven't noticed it since the day I posted this report. The day I posted it, it was pretty clear that it was happening, and only happening when BTT was open.

**Comment by sdrygalski** [comment]
@fifafu you can close this issue, it was my fault (and @fitzage too doesn't experience this bug anymore)

I had very long interval (maximum in fact) for double click and this was the reason trackpad behaving weirdly and I assumed it was another bug in betterTouchTool because it was very similar to another bug I reported here. So osx have somehow stupid behavior: you can't click another link/button if it waits for another click in previous button/link. Now I minimized time for doubleclick and everything works great.

Thank you for great software!

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or still encounter this problem, please create a new issue - I'm now much more responsive than a few months ago.
