### ISSUE TITLE
TipTap Left/Right (1 finger mix) with option/control/shift modifier doesn’t work for brightness up/down 

### ISSUE THREAD

**Issue by Korgun** [fifafu/BetterTouchTool#703]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
TipTap Left/Right (1 finger mix) with option/control/shift modifier doesn’t work for brightness up/down and if it's triggered multiple times it opens the display system settings
The same modifier does work for volume up/down
It does function as expected without modifiers

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad

#### Device information:

Type of Mac: MBP 15" with touchbar
macOS version: 10.12.3
BetterTouchTool version: 2.071 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hi,

sorry, this currently can't be fixed.
The problem is:

- The brightness up and down actions in BTT just produce a synthetic version of that key press. It's really just like pressing that key on a physical keyboard.
- Pressing the brightness up/down keys while holding modifier keys does not change the brightness but instead opens the display pane in the system preferences - this is system behavior and I don't think it can be changed.
