### ISSUE TITLE
Predefined Action "Move current window to current Desktop"

### ISSUE THREAD

**Issue by brandondrew** [fifafu/BetterTouchTool#717]
It is often the case that I select a window (from the window menu, from the Dock, or from Application Expose) that is on a different Desktop.

I would like a fast and easy way to move it to the current Desktop, and I'm hoping that BTT can make that possible.

**Comment by cleverjackal** [comment]
More of a workaround, but if you're trying to go to it using the application switcher, keep the alt button pressed while you release Command + Tab. Then you'll _go_ to that desktop, though.

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or still encounter this problem, please create a new issue - I'm now much more responsive than a few months ago.

Current versions of BTT have actions to move windows to specific desktops.
