### ISSUE TITLE
Bug/feature : keep keyboard layout when changing keyboard language

### ISSUE THREAD

**Issue by remirpn** [fifafu/BetterTouchTool#761]
#### Description of bug/feature request/question:

I often change keyboard language from FR to US but also, I use a plastic cover that change my keyboard layout from AZERTY to QWERTY.

However, when I change my language, BTT also change the keyboards shortcuts layout (W become Z etc)...and I can't use any of my actions anymore.

Is there I way to prevent BTT to change the layout when I change my keyboard language ?

**Comment by fifafu** [comment]
Unfortunately there is no way to achieve this. Shorcuts are bound by key codes, and unfortunately they are tied to the physical location of the key instead of the character of the key.

I have looked into this multiple times, but haven't found a good solution to make this work reliably. If I ever find one it will be added to BTT.
