### ISSUE TITLE
Tap sequences often send 3-finger tap as well

### ISSUE THREAD

**Issue by NevinBR** [fifafu/BetterTouchTool#796]
#### Description of bug/feature request/question:

Recently, since updating to BTT 2.09, when I activate my tap sequence gestures BTT will often also trigger a 3-finger tap immediately after. This manifests in a web browser as follows:

1. I use tap sequence 1234 (which sends cmd-shift-] ) to move to another tab
2. A 3-finger tap will also be registered (which sends Middle Click)
3. So if the cursor ended up over a link in the new tab, that link will immediately be opened in its own tab

The issue occurs frequently, but not every time.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

rMBP trackpad

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Late 2013)
macOS version: 10.12.4 (16E195)
BetterTouchTool version: 2.09 (616)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

If needed I can make a screen recording of this happening in the BTT gesture recognizer window.

**Comment by aitte2** [comment]
I can see it too in the "Live View" window of a macbook pro 2010 touchpad.

I roll 4 fingers on the trackpad and very often get a "3 finger tap: Middle click" detected, instead of just the "custom tap sequence (4 fingers)".

**Comment by fifafu** [comment]
Thanks for reporting, I'll look into this.

**Comment by SteveJobzniak** [comment]
Here's my testing:

MacBook Pro 2010: Tap sequence is pretty reliable. Sometimes detected as 4-finger tap and even more rarely as 3-finger tap.

Magic Trackpad 2: Tap sequence very unreliable, almost never detected at all, sometimes detected as 4-finger tap, maybe also as 3-finger tap but since it almost never registers at all when doing 4-finger sequences on the MT2 I wasn't able to see any 3-fingers detections.

The thicker circles (white outline) in the video are when I use the magic trackpad 2 instead.

[video.zip](https://github.com/fifafu/BetterTouchTool/files/924467/video.zip)

**Comment by SteveJobzniak** [comment]
This explains why I've always had to repeat the tap sequences about 1-3 times before they worked.

**Comment by fifafu** [comment]
I think this should be fixed in the current alpha (v2.095)
