### ISSUE TITLE
Remove the X button beside ESC

### ISSUE THREAD

**Issue by alenric** [fifafu/BetterTouchTool#875]
Hello there, I would just like to ask if there is a possibility to **remove the " x " button** beside ESC key **without** removing the MacOS control strip. Thank you

**Comment by fifafu** [comment]
Unfortunately this is not possible due to API limitations.
Only option is to hide the control strip.

Best
Andreas

Am 04.05.2017 um 16:14 schrieb alenric <notifications@github.com>:

Hello there, I would just like to ask if there is a possibility to *remove
the " x " button* beside ESC key *without* removing the MacOS control
strip. Thank you

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fifafu/BetterTouchTool/issues/875>, or mute the thread
