### ISSUE TITLE
Single click force touch

### ISSUE THREAD

**Issue by Nxt3** [fifafu/BetterTouchTool#88]
Would love the ability to map a single finger force click.

**Comment by pallavmac** [comment]
Unfortunately single click force touch is currently not possible. The problem is that there is no viable option to block the click that is produced by the system. This means a single click force touch would always also trigger a left-click, which makes it quite useless. Andreas can not block this because he cannot see whether the user is about to do a force click or a normal click :-(

**Comment by Nxt3** [comment]
Bummer. Makes sense though--I figured there was a technical reason this wasn't possible. Thank you!

**Comment by tarvos21** [comment]
I am also looking for this feather, since I have uses three-tap to look up words or preview a link, the single-finger force click on my macOS Sierra has not been used at all in any application, so I want to use single-finger force click to close one tab in Safari or iTerm2, it's will be really good because this gesture is very easy to make.

**Comment by yairchu** [comment]
> This means a single click force touch would always also trigger a left-click, which makes it quite useless.

Actually that could be great. For VS-Code I would like it to produce a left-click and then Cmd+T for jump-to-definition on the symbol I clicked...

**Comment by theonlygusti** [comment]
I would love to be able to map a force click, regardless of whether it's possible to block the previous click or not.

E.g. in finder I'd like to be able to re-map single finger force click to "Get Info" rather than preview.

**Comment by kcking** [comment]
+1 that not being able to block the first click is not a deal breaker, but I understand that it might confuse some users.

**Comment by theonlygusti** [comment]
@Nxt3 please reopen this

**Comment by fifafu** [comment]
Ok, I  should be able to add it without the click block. (I'll add a warning about that)

**Comment by fifafu** [comment]
I have added it with the latest alpha (2.315). It works great as cmd+click to open a new tab in browsers :-) (although many use cases are tricky to realize because of the mentioned left-click that always happens)

**Comment by RYJASM** [comment]
Is this still not possible? Single force click is an option to bring up the "look up" feature and yet it does not trigger a click. 2 finger force click lets you right click, but doesn't trigger a 2 finger click. It doesn't follow that this isn't possible, if it's already a feature of the OS.
